### ISSUE TITLE
Add Support for System Naming

### ISSUE THREAD

**Issue by drpoggi** [ibmdb/python-ibmdb#223]
This feature may or may not exist, but if it doesn't I'd like to suggest it. With the DB2 .NET driver you can do: 

``` C#
   DB2Connection myConnection = new DB2Connection();
   myConnection.ConnectionString = "DATABASE=SAMPLE;";
   myConnection.SystemNaming=true;
   myConnection.Open();
```

Which controls the following: 

> **True**
>       The DB2 for i system naming mode is used. File names are qualified with the slash (/) delimiter. Unqualified file names are resolved with the library list for the job.
> **False**
>     The SQL naming mode, which is the default value. File names are qualified with the period (.) delimiter. Unqualified file names are resolved with either the default library or the current user ID. 

Full documentation on that propery [here](http://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.swg.im.dbclient.adonet.ref.doc/doc/r0060653.html).

Is there an equivalent to doing `myConnection.SystemName=true;` in the Python lib and I'm just missing it?

**Comment by kadler** [comment]
System naming can be set by setting `SQL_ATTR_DBC_SYS_NAMING` connection attribute to `SQL_TRUE`. Since ibm_db provides a way to pass through connection attributes, you can specify this on `ibm_db.[p]connect` (using the `options` dict) or `ibm_db_dbi.[p]connect` (using the `conn_options` dict).

ibm_db does provide constants for some attributes, but not for `SQL_ATTR_DBC_SYS_NAMING`, so currently you'll have to look it up in the CLI header files. eg.

```
SQL_ATTR_DBC_SYS_NAMING = 10004 # On IBM i CLI. DB2 Connect may be different
ibm_db_dbi.connect(conn_options = { SQL_ATTR_DBC_SYS_NAMING: ibm_db.SQL_TRUE })
```


If using DB2 Connect, you'll have to look through the header files for their definition.

Of course, the best would be for us to define a constant in ibm_db like we do for other common attributes.

**Comment by kadler** [comment]
FYI, looks like `SQL_ATTR_DBC_SYS_NAMING` is `3017` on DB2 LUW/Connect.

**Comment by drpoggi** [comment]
@kadler Thanks for the quick support on this. That *somewhat* magic number worked for us.
