### ISSUE TITLE
Error while migrating from sqllite

### ISSUE THREAD

**Issue by milind7705** [ibmdb/python-ibmdb#226]
Hello,
My code is using the sqllite smoothly and there is a need to migrate it to DB2.
We have some existing migrations already created for the sqllite, but while applying those migration i am facing error. 
The scenario is : 
Created a sample model named "Employee" with emp_exists = models.BooleanField(null=True) and migrated the same to sqllite. After some more scenarios it is decided to change the emp_exists field to 
emp_exists = models.TextField(null=True). On changing the field, the migrations are created and applied to existing sqllite. 
On sqllite everything seems to work, but on db2 it is producing incompatible datatype issue. 
On further debugging, i found that BooleanField is being created as BLOB and TextField is created as CLOB. While altering the Employee table, the BLOB can't be assigned to CLOB and hence it was failed.

SQL generated while migrate command:
ALTER TABLE "EMPLOYEE" ADD COLUMN "PSUDO_EMP_EXISTS" CLOB
[]
UPDATE "EMPLOYEE" set "PSUDO_EMP_EXISTS"="EMP_EXISTS"

As its a migration, we can;t change the existing migrations. Could you provide any suggestions on how to proceed with the same?

**Comment by SabaKauser** [comment]
Hello Milind,
Can you share the repro or the model.

Thanks,
Saba.

**Comment by SabaKauser** [comment]
I tried a sample with boolean and here is what my model looks like:
from django.db import models

# Create your models here.

class Employee(models.Model):
    emp_name = models.CharField(max_length=128, null=False, blank=False, default="")
    emp_exists = models.BooleanField(null=False)

Here is the DDL that is generated:
CREATE TABLE "MYAPP_EMPLOYEE1" ("ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 10 ORDER) NOT NULL PRIMARY KEY, "EMP_NAME" VARCHAR(128) DEFAULT '' NOT NULL, "EMP_EXISTS" SMALLINT NOT NULL CHECK (emp_exists IN (0,1)))

And here is the model:
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('emp_name', models.CharField(default=b'', max_length=128)),
                ('emp_exists', models.BooleanField()),
            ],
        ),

I am not sure what is generating BinaryField for you.
To make boolean work with char, you can try using CharField(1) instead of TextField().

**Comment by milind7705** [comment]
Hello,
I modified some of the migrations and able to solve this issue.

Thanks and Regards,
Milind
