### ISSUE TITLE
UnicodeDecodeError: 'ascii' codes can't decode byte 0xb2 in position 28: ordinal not in range(128)

### ISSUE THREAD

**Issue by yyt030** [ibmdb/python-ibmdb#228]
when i catch the ibm_db.execute error message, it happen a error, pls help,

Env.:

```
os: windown 7
python: 3.5.2
ibm-db: 2.0.7
```

my code is below :
`

```
#coding: utf8 
import ibm_db
if __name__ == '__main__':
    sql_insert = 'insert into test(id) values(?)'
    data_insert = ('x',1)
    .... # my get conn function
    with get_conn() as conn:

        try:
            stmt = ibm_db.prepare(conn, sql_insert)
            ibm_db.execute(stmt, tuple(data_insert))
        except:
            print(ibm_db.stmt_errormsg())     

```

`

**Comment by yyt030** [comment]
http://stackoverflow.com/questions/37395235/python-and-ibm-db2-unicodedecodeerror

is this a bug ?

**Comment by IBMAmarPY** [comment]
Hello,

I created database in utf8 and run my testcase, I see values are inserting properly. Below is my testcase. Could you verify and let us know what difference in your environment/testcase.


#coding: utf8
import ibm_db

try:
  conn=ibm_db.connect('samv97','','')
  if conn:
    print("success")
    sql_insert = 'insert into test1(name,id) values(?,?)'
    data_insert = ('x',1)
    aTuple = tuple(data_insert)
    print(aTuple)
    try:
      stmt = ibm_db.prepare(conn, sql_insert)
      ibm_db.execute(stmt, tuple(data_insert))
      stmt1 = ibm_db.prepare(conn,"select * from test1")
      ibm_db.execute(stmt1)
      cols = ibm_db.fetch_tuple( stmt1)
      while cols:
        print("%s, %d" % (cols[0],cols[1]))
        cols = ibm_db.fetch_tuple( stmt1 )
    except:
      print(ibm_db.stmt_errormsg())
except:
  print(ibm_db.conn_errormsg())

**Comment by yyt030** [comment]
@IBMAmarPY , thanks for your reply
i type your above code and run it, but it is still being failed, the reason why is database samv97 not exist. 
but the code line is `print(ibm_db.conn_errormsg())  `
the conn_errormsg function cause UnicodeDecodeError exception.
in my first code above,  stmt_errormsg function  causing too.

my environment:
**os: windows 7**
python: 3.5.2
ibm-db: 2.0.7

what can i provide other infomations for deal with this fault?

While , i run you code on **SUSE linux,** but it is ok, Why?

**Comment by IBMAmarPY** [comment]
HI,

I tried to reproduce in win-64 bit (windows 7) with 32 bit python 3.5.1 version, ibm-db:2.0.7, but could not see the problem you are seeing.

C:\Users\IBM_ADMIN\AppData\Local\Programs\Python\Python35-32>python.exe
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> conn=ibm_db.connect('samv97','','')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: [IBM][CLI Driver] SQL1531N  The connection failed because the name sp
ecified with the DSN connection string keyword could not be found in either the
db2dsdriver.cfg configuration file or the db2cli.ini configuration file.  Data s
 SQLCODE=-1531cified in the connection string: "SAMV97".
>>> print(ibm_db.conn_errormsg())
[IBM][CLI Driver] SQL1531N  The connection failed because the name specified wit
h the DSN connection string keyword could not be found in either the db2dsdriver
.cfg configuration file or the db2cli.ini configuration file.  Data source name
 SQLCODE=-1531he connection string: "SAMV97".
>>> import sys
>>> print(sys.getdefaultencoding())
utf-8
>>> sys.stdout.encoding
'cp65001'
>>>

**Comment by yyt030** [comment]
HI,  thanks ,
```
import sys
print(sys.getdefaultencoding())
    utf-8
sys.stdout.encoding
    **'cp936'**
```

then , i change my pc **System Locale settings**,
the menu is:  Start >  Control Panel > Region and Language > Administrative tab
then change system locale and select the desired language, **from China to US**,

now , i print sys.stdout.encoding
**cp437**
run your code, and return OK.

Is there any other way deal with this problem?
