### ISSUE TITLE
Getting an import error with message: pthread_mutexattr_setkind_np: symbol not found

### ISSUE THREAD

**Issue by supercr7** [ibmdb/python-ibmdb#336]
Hi, I am running a docker image using Alpine LInux distro with python version `3.6.6`.

Full error text:
```
ImportError: Error relocating /usr/local/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1: pthread_mutexattr_setkind_np: symbol not found
```
I have `musl libc` installed as well. Any workaround for this? 

I came across this issue in `node-ibm_db` as well: https://github.com/ibmdb/node-ibm_db/issues/217. Is the behavior expected to be same for `python-ibmdb` as well? Please confirm if Alpine Linux is supported by `ibm_db` or not.

Thanks!

**Comment by SabaKauser** [comment]
Hello Harshit,

As I read from wiki, Alpine Linux uses uClibc as its C standard library instead of the traditional GNU C Library (glibc) that is most commonly used (the library clidriver (libdb2.so) is compiled on with glibc). The problem with symbols seems to be coming due to incompatibility of uClibc with glibc and it seems like to use clidriver on alpine, the driver must be compiled with uClibc, but we use glibc. 
If you just run db2cli tool, you should be running into same issue.

cd clidriver/bin
db2cli

**Comment by SabaKauser** [comment]
DB2 Connect(subset i.e libdb2.so in this case, a.k.a clidriver) is not supported on Alpine Linux.
The supported Operating systems are: 
https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=87FBA2009FE111E389FAED6C8DACE45F&osPlatform=Linux

**Comment by supercr7** [comment]
Thanks for your replies @SabaKauser.
