### ISSUE TITLE
Segmentation fault on more than one connection

### ISSUE THREAD

**Issue by ValentinDashinsky** [ibmdb/python-ibmdb#362]
Hi,
We are trying to open 2 connections to the same DB.
First connection is established successfully but the second connection throws a segmentation fault.
Tried on same thread and on 2 different threads (thread per connection)  and still getting the same exception.

This is an example of code that throws the exception:
```
import ibm_db

c1 = ibm_db.connect(... IBM_CLOUD_CREDENTIALS ...)
print("c1 = " + str(c1))

c2 = ibm_db.connect(... IBM_CLOUD_CREDENTIALS ...)
print("c2 = " + str(c2))
```

**Comment by SabaKauser** [comment]
can you share the stack trace.

**Comment by ValkA** [comment]
It seems to happen in the driver level.
Added the following code:
```
import faulthandler
faulthandler.enable()
```

Got the following error:
```
Fatal Python error: Segmentation fault

Current thread 0x00007fff9ae1a380 (most recent call first):
  File "/Users/valentid/PycharmProjects/CognitiveProfileSQL/ibmdbbug.py", line 8 in <module>
```

Tried to run it with LLDB (OSX, GDB alternative) but getting these errors which aren't related to the segfault since it happens in the first connection:
```
(lldb) target create ".../venv/bin/python"
Current executable set to '.../venv/bin/python' (x86_64).
(lldb) run ibmdbbug.py
Process 19737 launched: '.../venv/bin/python' (x86_64)
Process 19737 stopped
* thread #2, stop reason = exec
    frame #0: 0x000000010000519c dyld`_dyld_start
dyld`_dyld_start:
->  0x10000519c <+0>: popq   %rdi
    0x10000519d <+1>: pushq  $0x0
    0x10000519f <+3>: movq   %rsp, %rbp
    0x1000051a2 <+6>: andq   $-0x10, %rsp
Target 0: (Python) stopped.
(lldb) run ibmdbbug.py
There is a running process, kill it and restart?: [Y/n] Y
Process 19737 exited with status = 9 (0x00000009) 
Process 19741 launched: '/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python' (x86_64)
Traceback (most recent call last):
  File "ibmdbbug.py", line 5, in <module>
    c1 = ibm_db.connect("DATABASE=BLUDB;HOSTNAME=dashdb-txnha-flex-yp-dal10-59.services.dal.bluemix.net;PORT=50000;PROTOCOL=TCPIP;UID=bluadmin;PWD=YmQ4NmRhOGJhZjhl;", "", "")
Exception: [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3". SQLCODE=-1042
Process 19741 exited with status = 1 (0x00000001) 
(lldb) 
```

**Comment by SabaKauser** [comment]
can you collect traces as follows:

cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by ValkA** [comment]
Had an issue with 
`db2trc on -f trc.dmp`
Used `./db2trc on -i 2M` with `./db2trc dump trc.dmp` instead.
Dump formats seem to be pretty blank, not sure if I'm doing something wrong.

I've installed the libraries with `pip install ibm_db_sa` and using this env var to make it run on OSX:
DYLD_LIBRARY_PATH=/Users/.../Library/Python/3.6/lib/python/site-packages/clidriver/lib/icc
and ran db2trc from the above folder.

I have the same segmentation fault in IBM Cloud though, so I don't think its an OSX related issue.

[Archive.zip](https://github.com/ibmdb/python-ibmdb/files/2721017/Archive.zip)

**Comment by SabaKauser** [comment]
Hello,
When you turned the trace on, did the first connection succeed? If its the problem with second connection, we must get  data logged into db2 traces at least from the first connection.

I have used following and it worked for me:
db2trc on -l 2m
<repro>
db2trc dump trc.dmp
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli

**Comment by ValkA** [comment]
Python calls are not logged with `db2trc.`
When running `./db2cli` trace is filled with data but in python case, it remains empty.
Are there any flags that should be passed to `db2trc`?

**Comment by SabaKauser** [comment]
Traces not captured makes me think that python ibm_db driver is loading clidriver from a different location. If first connection from python ibm_db is successful, we should see entries similar to seen when invoking ./db2cli.

Have you faced seg fault earlier? Is this problem reproducible in other machines?
From the stack, the problem seems to be in Db2 client layer and its very unlikely.

Can you run this: edit file cli.txt, copy the contents below and execute as : ./db2cli < cli.txt
cat cli.txt
---------------
opt callerror on
opt echo on
sqlallocenv 1
sqlallocconnect 1 1 
sqldriverconnect 1 0 "database=dbname;hostname=hostname;uid=userid;pwd=password;protocol=tcpip;port=portno;" -3 255 SQL_DRIVER_NO_PROMPT
sqlallocconnect 1 2
sqldriverconnect 2 0 "database=dbname;hostname=hostname;uid=userid;pwd=password;protocol=tcpip;port=portno;" -3 255 SQL_DRIVER_NO_PROMPT

If the seg fault is seen with above script, collect db2 traces and share.

**Comment by ValkA** [comment]
Running `./db2cli<cli.txt` printed this to stdout:
```
18:13 $ ./db2cli < cli.txt 
IBM DATABASE 2 Interactive CLI Sample Program
(C) COPYRIGHT International Business Machines Corp. 1993,1996
All Rights Reserved
Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or
disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
> > > sqlallocenv 1
SQLAllocEnv: rc = 0 (SQL_SUCCESS) 
             CLI henv = 1, Test Driver henv = 1
> sqlallocconnect 1 1
SQLAllocConnect: rc = 0 (SQL_SUCCESS) 
             CLI hdbc = 1, Test Driver hdbc = 1
> sqldriverconnect 1 0 "database=BLUDB;hostname=***;protocol=tcpip;port=50000;" -3 255 SQL_DRIVER_NO_PROMPT
SQLDriverConnect: rc = 0 (SQL_SUCCESS) 
SQLDriverConnect: ConnStrOut:
 		*****
                  cbConnStrOut: 139
> sqlallocconnect 1 2
SQLAllocConnect: rc = 0 (SQL_SUCCESS) 
             CLI hdbc = 2, Test Driver hdbc = 2
> sqldriverconnect 2 0 "database=BLUDB;hostname=***;protocol=tcpip;port=50000;" -3 255 SQL_DRIVER_NO_PROMPTSegmentation fault: 11
```

Attached logs [Archive.zip](https://github.com/ibmdb/python-ibmdb/files/2724503/Archive.zip)


regarding the python traces, the DYLD that is loaded by python is:
`dyld: loaded: /Users/valentid/PycharmProjects/CognitiveProfileAPI_SQL/venv/lib/python3.6/site-packages/clidriver/lib/libdb2.dylib`
(extracted this using `DYLD_PRINT_LIBRARIES=YES /usr/bin/true` env var)

and the ./db2trc located in `/Users/valentid/PycharmProjects/CognitiveProfileAPI_SQL/venv/lib/python3.6/site-packages/clidriver/bin`

I believe they should use the same driver because of only one driver was installed with `pip install ibm_db`

**Comment by ValkA** [comment]
My db2level is
```
DB21085I  This instance or install (instance name, where applicable: "*") uses 
"64" bits and DB2 code release "SQL10055" with level identifier "0606010E".
Informational tokens are "DB2 v10.5.0.5", "special_35187", "DARWIN64105_35187", 
and Fix Pack "5".
Product is installed at 
"/Users/valentid/PycharmProjects/CognitiveProfileAPI_SQL/venv/lib/python3.6/sit
e-packages/clidriver".
```

Seems like an older version of the driver, which means `pip install ibm_db` downloads a broken driver.
What is the correct process to install the drivers in a python environment if its not `pip install ibm_db`?
In our case it's just a simple app that is running as IBM Cloud python app.

**Comment by SabaKauser** [comment]
The autodownload of clidriver on MAC is at db2_v10.5 level as seen in your db2level.
Tested the connections on the same level from my machine and it is success.
The driver is not broken.

>>> conn=ibm_db.connect(conn_str,'','')
>>> conn1=ibm_db.connect(conn_str,'','')
>>> print(conn)
<ibm_db.IBM_DBConnection object at 0x10dd9ebc0>
>>> print(conn1)
<ibm_db.IBM_DBConnection object at 0x10ddc9990>
>>> quit()


DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL10055" with level identifier "0606010E".
Informational tokens are "DB2 v10.5.0.5", "special_35187", "DARWIN64105_35187",
and Fix Pack "5".
Product is installed at
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/
ibm_db-2.0.9-py3.7-macosx-10.9-x86_64.egg/clidriver".

**Comment by SabaKauser** [comment]
you said you are able to see similar behavior on windows. If the problems are same, can you collect db2trc for ./db2cli < cli.txt

**Comment by ValkA** [comment]
On a windows 7 machine, did `pip install ibm_db`, it downloaded the following clidriver:
```
$ db2level.exe
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11013" with level identifier "0204010F".
Informational tokens are "DB2 v11.1.3031.295", "s1804271300",
"DYN1804271300WIN64", and Fix Pack "3a".
Product is installed at
"C:\Users\sela\anaconda3\envs\py37\Lib\site-packages\clidriver" with DB2 Copy
Name "IBM Data Server Driver For ODBC and CLI".
```

Ran `./db2cli.exe < cli.txt` as before, that is the stdout:
![image](https://user-images.githubusercontent.com/7328558/50831003-35a89f00-1352-11e9-8dac-1d536b156f76.png)
And it stucks there forever.

After few minutes of wait, got ~37MB of dump file:
[bin.zip](https://github.com/ibmdb/python-ibmdb/files/2736730/bin.zip)
![image](https://user-images.githubusercontent.com/7328558/50831074-6e487880-1352-11e9-8513-e38120b8eb0e.png)

This makes me think this might be integration with IBM Cloud issue, what DB2 are you connecting to? is it a local DB2? or an instance on IBM Cloud?

In my case its a Flex plan of DB2 on IBM Cloud.
If you're on IBM network I would be happy to work together to find the reason for the issue since this delays our development - valentin.dashinsky@il.ibm.com

**Comment by ValkA** [comment]
The cause of the issue was that we were creating 2 parallel SSL connections.
Using "PORT=50001;Security=SSL;" in the connection string allows us to open 2 connection from db2cli.

But using that connection string in python throws the following exception:
`Exception: [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3". SQLCODE=-30081`

**Comment by SabaKauser** [comment]
Is there any assistance needed on this?

**Comment by ValkA** [comment]
Issue solved. When connecting to DB2 on IBM Cloud use SSL connection.

**Comment by SabaKauser** [comment]
Thanks!
