### ISSUE TITLE
multiple calls to ibm_db_dbi.columns() - Fatal Python error: Deallocating None

### ISSUE THREAD

**Issue by romatho** [ibmdb/python-ibmdb#413]
Hello everyone,
I'm working with ibm_db_dbi to insert values into timeseries on informix. When I call too many times the function  ibm_db_dbi.columns(), I end-up with the following mistake: Fatal Python error: deallocating None.  I'm working with Python 3.6.8. I created the following simple code that generate the error.
`while True:

conn_str = "server=informix;database=analytics;hostname=" + database_hostname + ";port=" + database_port + ";protocol=TCPIP;UID=informix;PWD="+ informix_pwd
	ibm_db_conn = ibm_db_dbi.connect(conn_str,"","")
	ibm_db_conn.columns(table_name='vt_alarm_measure')
	ibm_db_conn.close()        
`     
(I also tried it with a single connexion before the loop and the result is exactly the same.)
Since the problem happens after a lot of calls to the function, I could not generate the various Trc dump files (the .dmp file reached a size of 8.5gb)

**Comment by SabaKauser** [comment]
@romatho , why do you need to call ibm_db_dbi.columns() in a while loop for the same table?

**Comment by romatho** [comment]
@SabaKauser The while loop is  just a simple code to recreate the error. Basically I'm working with a module developed in my company which provide functions to fetch and insert row in time series. Basically, the sql request are generated in the module which only receive raw data to insert and the name of the table. Therefore this module calls  the columns function multiple times. I'm trying to test the performance of informix when it faces regular inserts and this leads to many calls to the columns function. I can get around the problem but I was interested to see what i could do to continue using the columns function.

**Comment by SabaKauser** [comment]
I will try to reproduce.

**Comment by imavo** [comment]
This symptom is easily reproducible with ibm_db v3.0.1 on python 3.6.9
and also with ibm_db v2.0.9 on python 2.7.12.
(in my case the target database is on Db2 locally).

When python crashes I see this:

> 
> Fatal Python error: deallocating None
> Aborted (core dumped)
> 

On ubuntu 16.04 with python 2.7.12 I get a popup indicating the crash and inviting me to submit error details.
I attach a screenshot because it shows some of the stacktrace.

On ubuntu 18.04 LTS with python 3.6.9, I get the crash for every run, though the number of loop iterations varies.
During the run, I notice that the RSS figure as reported by `ps` rises steadily.
