### ISSUE TITLE
Installing without DB2 drivers

### ISSUE THREAD

**Issue by ramazanpolat** [ibmdb/python-ibmdb#470]
We need to install this driver for auto-code-completion in IDE.
The code runs on remote server and remote server HAS a DB2 driver.
So it can connect to DB2 without any problem. 

For developers, we don't need to install DB2 drivers simply because the we write does not get executed on our desktop. It gets executed on remote server which has access rights to DB2 server.

**TL;DR**
Is there any way to install `ibm_db` without installing DB2 drivers?

**Comment by SabaKauser** [comment]
Hi,
Yes, you can install ibm_db without installing Db2 Drivers, however, in order to do so, you should have an existing installation which the driver setup can refer to.
Set IBM_DB_HOME environment variable to point to existing installation of db2 driver or db2 server.
You  can find more information here  -> https://github.com/ibmdb/python-ibmdb#envvar

**Comment by ramazanpolat** [comment]
That means I need to have an existing DB2 drivers installation. So the answer is NO, I cannot have an installed `ibm_db` python module without a DB2 driver installation.
