### ISSUE TITLE
DB2 Connect license applied, still cannot connect to DB2 z/OS

### ISSUE THREAD

**Issue by deliego** [ibmdb/python-ibmdb#525]
Hi there,
I know this is a common issue with the error "license problem" but it is not very clear on solving it.

1. Linux machine has an app that will connect to a remote DB2 on a z/OS machine.
2. ibm_db was installed to run the app.
3. ibm_db/clidriver/bin/db2level says DB2 code release "SQL11014" for "DB2 v11.1.4.5"
4. License applied to ibm_db/clidriver/license/
5. Content of license certificate says: ProductVersion=11.1

Per IBM's instructions, the license should be added using db2licm, right? But this is not in the ibm_db package. So what else do we need to install on that linux machine? Are we missing another product to get the tool to register licenses?
Is it also expecting an IBM_DB_HOME env variable? or is that only needed for local DB2 systems?
What else besides placing the license file into clidriver/license/ directory should be done?

Any help is appreciated.

Thanks!

**Comment by SabaKauser** [comment]
Hi,
For odbc and clidriver, you just need to copy the client license under the license directory and you should be able to connect. If this is not happening in your environemnt, kindly collect traces and share.

IBM_DB_HOME is needed for avoiding install time dependency of clidriver for compiling the driver source code. If you have an existing installation that would like to point to, you can set that in IBM_DB_HOME and ibm_db driver will not install the clidriver under site-packages.

To collect trace:
cd `clidriver install path, found under site-packages of ibm_db install location or any other copy that you are using via IBM_DB_HOME`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files with us to assist you further.

**Comment by deliego** [comment]
Thanks @SabaKauser . Where should I send them? They are quite large

**Comment by deliego** [comment]
I got your email from another thread. Sent the trace to your email. Thank you.
Confirmed that the license applied is db2consv_zs.lic

**Comment by SabaKauser** [comment]
Hi,
From the traces I see this:
2206	data DB2 Common OSSe ossGetFileInfo cei (3.1.3.31.2.20)
	pid 54201 tid 140149656635136 probe 20
	bytes 127

	Data1 	(PD_TYPE_DEFAULT,119) Hexdump:
	2F6F 7074 2F64 796E 6174 7261 6365 2F72    /opt/dynatrace/r
	656D 6F74 6570 6C75 6769 6E6D 6F64 756C    emotepluginmodul
	652F 706C 7567 696E 5F64 6570 6C6F 796D    e/plugin_deploym
	656E 742F 6375 7374 6F6D 2E72 656D 6F74    ent/custom.remot
	652E 7079 7468 6F6E 2E64 6232 5F69 6E73    e.python.db2_ins
	6967 6874 732F 636C 6964 7269 7665 722F    ights/clidriver/
	6C69 6365 6E73 652F 6462 3263 6F6E 7376    license/db2consv
	5F7A 732E 6C69 63                          _zs.lic

And this license file seem to be valid for a V10.1 version. Can you correct the Library path to pick the correct clidriver library or copy the license file into the license folder of the clidriver that is being used as per traces.

Thanks!

**Comment by deliego** [comment]
Thanks Saba. The license is in that path, that is the correct path and the file is already in it.
Do you mean another path that is not listed?

db2level says that the DB2 code release loaded is 11.1.4.5.
The license file says ProductVersion: 11.1 in it.

I'm not sure if I am understanding this correctly, your suggestions are already in place. Path is correct, license file is in that path and readable. License says it's for 11.1, DB2 connect that came with ibm_db says it's 11.1.4.5.

What else could it be?

**Comment by SabaKauser** [comment]
Hello @deliego ,
The license picked from that path is reporting that it is valid for a V10.1 client.
From your traces:

2214	data DB2 UDB license manager sqllcGetVersionFromECF fnc (3.3.173.155.0.10)
	pid 54201 tid 140149656635136 cpid -1 node -1 probe 10
	bytes 12

	Data1 	(PD_TYPE_DEFAULT,4) Hexdump:
	3130 2E31                                  **10.1**

Can you please email me the license file or cross-verify the exact path and license files content once again. Can you also check if you have a nodelock file under license directory and renaming the same to something else resolves the issue?

**Comment by deliego** [comment]
Thank you. I'm awaiting to receive the files. You are correct that the license is for 10.1. The first time the license was for 11.1.4.5 but that failed with the same error. Once we created the trace, one of the files said:
```
[ Process: 23987, Thread: 139682788660992 ]
[ Date & Time:               06/25/2020 10:22:01.594323 ]
[ Product:                   QDB2/LINUXX8664 DB2 v11.1.4.5 ]
[ Level Identifier:          0205010F ]
[ CLI Driver Version:        10.01.0000 ]
[ Informational Tokens:      "DB2 v11.1.4.5","special_39510","DYN1911120100AMD64_39510","Fixpack 5" ]
[ db2cli.ini Location:       db2cli.ini file not found. ( rc = 100 ) ]
[ CLI Driver Type:           IBM Data Server Driver For ODBC and CLI ]
```
So we noticed that the driver in the ibm_db bundle was 10.1 and we switched licenses to 10.1 for that reason, but we received the same error. We created a new trace and that is the one I sent you.
I will send you the files if I can once I receive them.

**Comment by deliego** [comment]
Sent licenses. No nodelock files in the directory.

**Comment by deliego** [comment]
Did you notice anything in the licenses?

**Comment by SabaKauser** [comment]
I did not get time to use your license files. I will validate and let you know.

**Comment by deliego** [comment]
Thanks Saba. I'm not sure if you'd be able to use them but maybe you can spot something strange in them.
Do licenses need to be managed or installed on the client side using db2licm? We just placed the file in the license directory, we didn't "add" a license through the management command tool.

**Comment by imavo** [comment]
A much easier option: As you are using a Db2-connect-unlimited license (db2connsv_zs.lic) ,  consider using the `db2connectactivate` tool (available in the Db2-connect activation package image available on Passport Advantage) per target subsystem/database, because that will entirely eliminate the need for workstation-side licensing for connections to the target Db2-for-Z subsystem.  See the Db2 Knowledge centre for details, because careful planning is essential. Most likely your Z-DBA will already be aware of this scheme.  If you are unable to achieve this, then read on.


Verify that your linux hostname does not have multiple Db2-products installed (i.e the Db2 runtime client, or a Db2 data server client). If either of these are installed, they may have entries in the environment that may confuse clidriver.  Your question does not explicitly state what is installed apart from clidriver. If at least one such Db2-client is already installed in your linux hostname then you must choose what to do. Either use that pre-existing Db2-client (and do NOT use clidriver, and remove and re-install ibm_db with IBM_DB_HOME pointing to your pre-existing Db2-client), or uninstall the pre-existing Db2-client and only use clidriver that comes with ibm_db module by default. Don't try a combination of both unless you are an expert at managing the environment variables, ld_library_path etc. If you do have a separate Db2-client installed (other than clidriver) and you want to use that Db2-client with python, then your "db2connsv_zs.lic" version must match the db2level output of your Db2-client (major+minor version).

If you have no other Db2-client installed in your linux hostname, and you are only using clidriver, Verify that only a single copy of file "db2connsv_zs.lic" exists on your linux tree (search from root if necessary). If there are multiple copies of that license file, remove or rename them so that they cannot be loaded in error. Verify that the "db2connsv_zs.lic" copy in clidriver/license has matching version number with clidriver/bin/db2level .

**Comment by deliego** [comment]
Thanks @imavo. The only reason we have that db2consv_zs.lic is because that is what the other reported issues on this github said to use. However, we can use any other type if needed.
No client or run-time client or data server was installed, that's why I didn't list it in my question. The only thing that was used was ibm_db so whatever ibm_db comes with (cli driver). I assume we do not need to install any of those clients, do we?
ibm_db's clidriver/bin/db2level says that the driver in it is 10.1, but the product is QDB2/LINUXX8664 DB2 v11.1.4.5, so which license for what version do we need to use? 10.1 to match the "Driver", or 11.1.4.5 to match the "Product"?

We only have one license in that location and we have tried with **10.1** and **11.1** licenses (note, no 11.1.4.5, just 11.1)
:
```
[root@server license]# ls -ltr
total 68
-rwxrwxr-x. 1 root root  1000 Feb 10  2017 db2consv_zs.lic
-rwxr-xr-x. 1 root root  1854 Jun 12 08:56 odbc_REDIST.txt
-rwxr-xr-x. 1 root root 23865 Jun 12 08:56 odbc_notices.txt
-rwxr-xr-x. 1 root root 25738 Jun 12 08:56 odbc_notices.rtf
drwxr-xr-x. 2 root root  4096 Jun 12 09:03 UNIX
drwxr-xr-x. 2 root root  4096 Jun 12 09:04 Windows
```

**Comment by imavo** [comment]
Please do talk with you Z/DBA to arrange for the simpler solution of db2connectactivate.

You do not need to install any other Db2 product on your linux hostname. clidriver should be enough (once correctly licensed for Z connectivity,  either with workstation side licensing as your are trying, or with the host-side licensing via db2connectactivate which I recommend).

It is important to verify that no other Db2 product is installed (other than clidriver, which is just an unzip action to install this tiny driver).

According to saba's updates, the db2 trace showed that the *license file for Db2-connect* was for v10.1 so that cannot work with a clidriver v11.1.4.5, so I would expect SQL1598 errors. 

But, if you carefully verify that a single copy of "db2consv_zs.lic" exists, and it is version for v11.1 and you are using a v11.1.4.5 clidriver then __it should work__, and if SQL1598n still occurs with a `db2cli validate -dsn XXX -connect -user ... -passwd ...` then you should open a ticket with IBM support directly (as that has nothing to do with python). Additionally if you take a db2trc and it confirms that the db2consv_zs.lic license file is valid for a V11.1 client, and you still get SQL1598N then IBM defect support should respond.  

Hopefully you understand that your configuration issue has nothing to do with python or ibm_db, and everything to do with how you have your clidriver licensed. Remember that clidriver is not specific to python and can be used without python (and validated and tested with its db2cli command line tool as described in the Db2 knowledge center).

**Comment by deliego** [comment]
Thanks @imavo. I will test the connection that way and let you know what we find out.

**Comment by SabaKauser** [comment]
@imavo thanks for the detailed explanations. I am sure @daliego finds them helpful.
@daliego, there are 2 types of licenses. One is copied at client's license directory and is in the form of a file that you are using. This should match the client driver version and has nothing do with Server version as you would have already bought separate server side license.  
db2licm is for clients (IBM data server client, IBM Data Server Runtime client) as well as for server editions. 
For clidriver and IBM Data Server Driver(basically driver packages), you are required to copy the license files under license directory of corresponding installations that you intend to use for database connections.

db2connectactivate activates a SP at database server and if you have activated the license from say v11.1 version of client, the license allows you to connect to the database server from lower level clients as well.

From my analysis of the traces, you used a V10.1 license from a v11.1 client and the license error is expected for file type license.

**Comment by deliego** [comment]
Excellent, the `db2cli validate` command helped resolve the issue. The initial 11.1 license was not correct and using a new one worked and connected.
Thanks for all your help!

Closing it.
