### ISSUE TITLE
Python Secure to Db2 for z/OS GSKit Error: 201

### ISSUE THREAD

**Issue by neoEvol** [ibmdb/python-ibmdb#529]
SQLCODE=-1109M][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "GSKit Error: 201".  SQLSTATE=42724

that's the error i've received, and i cannot seem to get around it.  
i went after the 201:
201 - GSK_NO_KEYFILE_PASSWORD
Neither the password nor the stash-file name was specified, so the key file could not be initialized.

looking at SSLClientKeystoredb, I've tried either and both combos of the stash / keystore pw.  i continue to get the above error.

Im running anaconda python 3.7 on windows 10.  

i look in the db2diag.log file, i see errors but i don't know how to interpret them.

Everything seems fine/where it should be.  Please help

Thank you very much,

**Comment by imavo** [comment]
Your issue has nothing to do with python, and everything to do with client-side configuration for SSL/TLS for Db2.  Your question does not give enough details about your Db2 client configuration. Connecting from Windows-10 to Db2 encrypted with SSL/TLS works correctly if configured properly.

When working with SSL/TLS and Db2 it is wise to get the encyrpted connection working first at the command line (for example, using the db2cli tool along with configuring the xml file called db2dsdriver.cfg).  Both are described in the Db2 Knowledge Center.  When you can connect to the database at the command line (for example with `db2cli -validate -connect ....`  then python + ibm_db +clidriver will just work as all the configuration work has already been completed.

If you are unable to work with command lines or edit XML files, then you should edit your question to add your python code for the connect action (mask the hostname/IP-address).

It is usually simpler to configure SSL/TLS by using the SSLSERVERCERTIFICATE attribute instead of manually creating and populating a keystore/stash file. The value of the attribute is the fully qualified path to the certificate file on your workstation. This causes the Db2-driver to dynamically create a single-use keystore for you, and you then do not need to use your own keystore/stash.

As you are connecting to Db2 for Z/OS, you will either need a suitable licence file on your workstation for clidriver to use, or alternately connect via a pre-existing Db2-connect gateway.

**Comment by SabaKauser** [comment]
@imavo you are correct. 
@neoEvol you can refer this:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.db2.luw.wn.doc/doc/c0060895.html

You can extract the server certificate from server and copy it in client machine. Use that certificate in SSLServerCertificate keyword value. 
Example can be found here:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.1.0/com.ibm.db2.luw.admin.sec.doc/doc/t0025241.html

**Comment by neoEvol** [comment]
@imavo 
@SabaKauser 
Thank you for your response.  Let me work through imavo's suggestion.  may take a few days, but i'll respond here to update my success (or not).

Thanks again!!

**Comment by neoEvol** [comment]
Hello @imavo & @SabaKauser ,

I'd like to proceed with going the db2cli method as mentioned above.  I'm running into trouble doing anything in the CLI.  when i open the db2cli.exe i see this message:
IBM DATABASE 2 Interactive CLI Sample Program
(C) COPYRIGHT International Business Machines Corp. 1993,1996
All Rights Reserved
Licensed Materials - Property of IBM
US Government Users Restricted Rights - Use, duplication or
disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

then i try to execute db2cli -help and i get this error:
> db2cli -help
Syntax Error: First token is not a valid command !
>

It doesn't seem like i can do anything in the CLI.  

what im trying to do now is create a new .cfg for the particular database i want to connect to, then validate via the CLI tool.

What is the first token not valid all about?  canyou provide any other guidance?

Thanks so much

**Comment by imavo** [comment]
Must be something to do with your environment (anaconda /python Windows10 ?).
Works fine for me `db2cli -help` on Win10 pro. 
In any case, for help, best to study the docs at https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.admin.cmd.doc/doc/r0002045.html

You can edit the db2dsdriver.cfg with any xml editor or text editor (in addition to manipulating the file with db2cli command lines but I find them more awkward that just editing the xml file with an editor). Plenty of examples of db2dsdriver.cfg contents if you google.

One clarification:  are you trying to use 'certificate authentication' with Db2 for Z/OS , or do you have a working userid/password for connecting to the database?

**Comment by neoEvol** [comment]
I'm not trying ot use a cert yet: i have ID/pwd to connect to unsecure DB first.  Once i get that going, i'll improve to secure.

one thing i'm curious about is the top line of the cli when i open it:
IBM DATABASE 2 Interactive CLI Sample Program

sample program, makes me think im not in the right spot.

Yes, i have windows ten, anaconda.  i was looking for doc on the CLI, so i'll check that out and see where i land.

You'll be hearing back from me soon =)  thank you so very much!

**Comment by neoEvol** [comment]
OK, lets pretend i never asked about the CLI-not-working trouble:

 instead of using the cmd provided, i used a blank one, cd'd into the directory, and db2cli -help works fine now.

I'm going to see if my .cfg and .ini works now.

**Comment by neoEvol** [comment]
OK, this has been solved.  Thank you.

**Comment by SabaKauser** [comment]
for users reference, if you can add details of what resolved the issue for you?

**Comment by neoEvol** [comment]
I'm still getting the same error, this is not resolved.  Above it was noted i my problem is with the client configuration, and that i should start with the CLI.  I've done that.  I'm having trouble there too, and opened issue # 530 for secure.  i just added a comment there.  i figured the CLI issue is different than this one, so i opened a new item on it.  i'd liek to solve both the CLI and python issue.  i'll chat in either ticket if you'd like.  

If yo don't mind my asking, Do you work for IBM?

**Comment by neoEvol** [comment]
my issue was with how my cert was implemented.  Be sure you are aware all your config is correct.
