### ISSUE TITLE
Connecting to PUB400.com exceptions

### ISSUE THREAD

**Issue by Ryanb58** [ibmdb/python-ibmdb#555]
Hello, I am trying to use this library to reach out to a remote test server located at pub400.com. However, when I call `.connect` the following error occurs. Has anyone else had this issue or know how to get around it? I've been spinning my wheels for a few days on it.

I am able to telnet to the IP address using ports 449, 8471, and 9471 just fine.

**Code:**
```
import ibm_db
import ibm_db_dbi

db = (
    "DRIVER = {DB2};"
    "DATABASE=********;"
    "HOSTNAME=www.pub400.com;"
    "PORT=9471;"
    "PROTOCAL=TCPIP;"
    'UID=*******;'
    'PWD=*******;'
    'SSL=1'
)

ibm_db_conn = ibm_db.connect(db, "", "")
```

**Exception:**
```
root@694f2427063d:/data/web# python connect_to_ibm_i_instance.py
Traceback (most recent call last):
  File "connect_to_ibm_i_instance.py", line 26, in <module>
    ibm_db_conn = ibm_db.connect(db, "", "")
Exception: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "185.113.5.134".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001 SQLCODE=-30081
```

I have tried several different versions of that connection string with no prevail. 

I have also tried this in a docker container running python 2.7 and again on my host machine with Python 3.7.

**Comment by imavo** [comment]
Do you have `IBM i access` for unix/linux already installed locally and configured to successfully connect to the remote Db2-for-i ? 
If not, you need to do that first, before you try with the odbc driver supplied by `IBM i access` product, and specify that driver in the connection-string in Python. This is a FAQ.

**Comment by Ryanb58** [comment]
@imavo I believe I already have it setup.

I am grabbing the IBM I Access for unix/linux from the following url:
https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz

Some more info from my ini files:

odbcinst.ini:
```
# Example odbcinst.ini driver definition for DB2 Data Server Driver for ODBC and
# CLI
[DB2]
Description=DB2 ODBC Driver
Driver=/home/db2_cli_odbc_driver/clidriver/lib/libdb2.so
Fileusage=1
Dontdlclose=1
```

odbc.ini:
```
[IBM DB2 ODBC DRIVER]
Driver=DB2
```

I just tried to access my database from the terminal using `isql` and it spits out the following.
```
root@694f2427063d:/data/web# isql -v DB2 USERNAME PASSWORD
[IM002][unixODBC][Driver Manager]Data source name not found, and no default driver specified
[ISQL]ERROR: Could not SQLConnect
```

**Comment by kadler** [comment]
@Ryanb58 That's _not_ the IBM i Access Driver. The IBM i Access driver is available from https://ibm.biz/ibmi-odbc-download
Also, your ports are wrong to use the Db2 Connect driver. If you want to use that driver, you need the DRDA port, which is 446/448 (TLS).

I would recommend using the IBM i Access driver + pyodbc instead of ibm_db as ibm_db will use the Db2 Connect drivers which  requires a very expensive license when connecting to IBM i.

We have more documentation on using the IBM i Access driver here: https://github.com/IBM/ibmi-oss-examples/blob/master/odbc/odbc.md

**Comment by Ryanb58** [comment]
@kadler Thank you for that insight. Following your instructions on using the IBM i Access Driver + pyodbc ended up working beautifully and I was able to connect to pub400.com with ease. 

Thank you very much for your time and energy with this issue.

For anyone else that looks at this issue, here is the code I used to test my setup once connected

```
import pyodbc

cnxn = pyodbc.connect('DRIVER={IBM i Access ODBC Driver};SYSTEM=www.pub400.com;UID=TAYLORB;PWD=*****')
cursor = cnxn.cursor()

cursor.execute("select * from TAYLORB1.people")
rows = cursor.fetchall()
for row in rows:
    print(row)
```

**Comment by drpoggi** [comment]
@kadler When connecting to IBM i are there any performance differences between connecting using pyodbc + IBM i Access Driver vs ibm_db + clidriver/Db2 Connect with a license file? What advantages does the license get you when there's a free alternative?

**Comment by kadler** [comment]
The license you need is for Db2 Connect Unlimited for System i. This is the most comprehensive version of Db2 Connect that there is, so you get access to all the goodies that that entails. You can perhaps find out more here: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.qb.dbconn.doc/doc/c0008447.html

Whether those features are useful or not, I couldn't say. I think most of our customers just want a simple way to connect to their system and the IBM i Access driver works for them.

One major difference when using the IBM i Access driver is that you can't use it with the Db2-specific language interface (eg. ibm_db for Python) but instead must use the database-agnostic ODBC interface. ODBC interfaces are designed to work with multiple databases and sometimes limited to the lowest common denominator (eg. PyODBC doesn't support output parameters due to how MSSQL works conflicts with how PEP-249's callproc API is defined). Everything must be done through standard SQL interfaces as well usually, since these generic interfaces won't have any db-specific APIs (eg. ibm_db has APIs like [createDb](https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbcreatedb)).

One other difference between the Db2 Connect driver and the IBM i Access driver is ports used. Db2 Connect uses DRDA, which is on one port (446/448) while the IBM i Access driver uses various host server ports. This should really only matters for firewalls, but it is a difference to be aware of.

As to performance, I haven't done any benchmarks comparing the two but I'd expect them to be similar.

**Comment by drpoggi** [comment]
Perfect, thank you for the thorough explanation!
