### ISSUE TITLE
Communication function detecting the error: "sqlccSSLSocketSetup"

### ISSUE THREAD

**Issue by innjoshka** [ibmdb/python-ibmdb#569]
I try to conncet to db2 database via python-ibmdb with self-signed certificate saved in .jks. 

Package versions:
python==3.6.9
ibm_db==3.0.2

OS: Ubuntu 18.04.4 LTS

conn_string = (
    f"DRIVER={{IBM DB2 JDBC DRIVER}}"
    f";DATABASE={get_var('DSN_DATABASE')}"
    f";HOSTNAME={get_var('DSN_HOSTNAME')}"
    f";PORT={get_var('DSN_PORT')}"
    f";PROTOCOL=TCPIP"
    f";CONNECTTIMEOUT=10"
    f";UID={get_var('DSN_UID')}"
    f";PWD={get_var('DSN_PWD')}"
    f";SECURITY=ssl"
    f";sslTrustStoreLocation=/home/xxx/xxx/xxx/crt/certificate.jks"
    f";sslTrustStorePassword={get_var('SSL_PSWD')}"
)

When I try to connect to db2

`
conn = ibm_db_dbi.connect(conn_string, '', '')`

I get error:

> ibm_db_dbi.OperationalError: ibm_db_dbi::OperationalError: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001 SQLCODE=-30081

Have tried **sslTrustStoreLocation** with absolute &  relative paths. Before adding sslTrustStoreLocation & sslTrustStorePassword all worked fine but currently certificate has to be passed to connect to db2. I want to stress that connection link was properly and conncetion was before adding certificate. Also tried .jks and .crt 

The .jks file works great, so IBM lift and R language with  RJDBC/DBI have successful connection. The only package that does not work is python ibmdb. Could you navigate and explain what I'm doing wrong?

**Comment by amukherjee28** [comment]
Hi,

In order to make SSL Connection to DB2 Database with Self Signed Certificates please try to use the following key words combination in the connection string.

1. USING SERVER CERTIFICATE  : 

USE KEYWORD : **SSLSERVERCERTIFICATE**

DATABASE=DATABASE_NAME;HOSTNAME=HOST_NAME;PORT=SSL_PORT_NUMBER;SECURITY=SSL;SSLServerCertificate=FULL_PATH_TO_CERTIFICATE;UID=newton;PWD=A2m8test

2. USING KEYSTORE :

USE KEYWORD : **SSLCLIENTKEYSTOREDB** and **SSLCLIENTKEYSTOREDBPASSWORD**

DATABASE=DATABASE_NAME;HOSTNAME=HOST_NAME;PORT=SSL_PORT_NUMBER;SECURITY=SSL;SSLClientKeyStoreDB=FULL_PATH_TO_KEY_STORE_DB;SSLClientKeyStoreDBPassword=PASSWORD;UID=newton;PWD=A2m8test

Please have a look at the SSL keywords supported by db2 in connection string and db2dsdriver.cfg file.

https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0061826.html

Please check by replacing the connection string once with the above mentioned keywords.

Thanks.

**Comment by innjoshka** [comment]
@amukherjee28 Hi,

Thanks for your help, I have tried all what you have suggested and gave to read

unfortunately, I could not succeed.

i have tried:
1. **KEYWORD** SSLSERVERCERTIFICATE
conn_string = (
    f"DRIVER={{IBM DB2 JDBC DRIVER}}"
    f";DATABASE={os.getenv('DSN_DATABASE')}"
    f";HOSTNAME={os.getenv('DSN_HOSTNAME')}"
    f";PORT={os.getenv('DSN_PORT')}"
    f";CONNECTTIMEOUT=15"
    f";SECURITY=SSL"
    f";UID={os.getenv('DSN_UID')}"
    f";PWD={os.getenv('DSN_PWD')}"
    f";SSLSERVERCERTIFICATE=FULL_PATH_TO_CERTIFICATE.cfg"
) 

2. 
 **KEYWORD** SSLCLIENTKEYSTOREDB and **KEYWORD** SSLCLIENTKEYSTOREDBPASSWORD
conn_string = (
    f"DRIVER={{IBM DB2 JDBC DRIVER}}"
    f";DATABASE={os.getenv('DSN_DATABASE')}"
    f";HOSTNAME={os.getenv('DSN_HOSTNAME')}"
    f";PORT={os.getenv('DSN_PORT')}"
    f";CONNECTTIMEOUT=10"
    f";UID={os.getenv('DSN_UID')}"
    f";PWD={os.getenv('DSN_PWD')}"
    f";SECURITY=ssl"
    f";SSLClientKeystoredb=FULL_PATH_TO_CERTIFICATE.jks"
    f";SSLClientKeystoreDBPassword=SSL_PSWD"
)

3. Change place of these keywords in the connection string

4. Add single quotes inside path to certificate such as 'FULL_PATH_TO_CERTIFICATE.cfg'

5. Also tried .cfg change to .jks for both 1st and 2nd choices

--------

Unfortunately, Connection cannot be established

ibm_db_dbi.OperationalError: ibm_db_dbi::OperationalError: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "XXXXXX".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001 SQLCODE=-30081

It's seen that file is correctly read by ibmdb package but nothing else happens

If you have any ideas what can be tried, that will be awesome. 

Thanks in any case

**Comment by amukherjee28** [comment]
Hi,

In order to check more on this I would like to get a few details :
1. I could not help to notice the use of DRIVER = IBM DB2 JDBC DRIVER in the connection string.
Are you using the JDBC driver and then using python to connect to database ?

2. Can you please help me understand a bit more on how you have obtained the certificate?

3. What kind of server are you connecting to ? 

Please provide me with these details to understand the problem statement bit more.

Thanks.

**Comment by innjoshka** [comment]
@amukherjee28 Sorry for writing it after an hour. I accidentally made a mistake with credentials to connect. Tried to connect with different env creds and obviously I was failed. Currently all works fine. By the way It works with both choices (I wrote those choice strings in a comment below)

Thanks  for your help, you can freely close this issue

**Comment by amukherjee28** [comment]
cheers then 👍 

Thanks for the conformation.
