### ISSUE TITLE
An attempt to connect to the database server failed because of a licensing problem.

### ISSUE THREAD

**Issue by blhack** [ibmdb/python-ibmdb#582]
Error is: SQL1598N

Can anybody tell me which software product I need from IBM to get a license for this?  I have an email thread going with a sales person at IBM, but they are telling me that I need client access enterprise edition, with a minimum of 25 licenses, and it appears to be a yearly subscription that has a *substantial* cost (per year).  It seems like they're mostly unaware of this python module, and don't understand what I'm actually asking them for.

The README here says to "contact sales", but it doesn't tell me what to actually ask them for, and it seems like I'm probably asking them for the wrong thing.  To make this a pull-requestable issue specific to this repo: the README doesn't indicate what request to make of sales once they are contacted and, in that way, seems incomplete.

**Comment by shilumathai** [comment]
Python driver(ibmdb) needs Db2 Connect license to connect to Db2 for z/OS and Db2 for i. Below link has part numbers for different Db2 Connect License/package options
https://www.ibm.com/support/pages/downloading-ibm-db2-version-115-linux-unix-and-windows

What you probably need is 

CC1UYML 	IBM® DB2 Connect™ Enterprise Edition - Activation 11.5 for Linux®, UNIX and Windows® 

Usually Enterprise edition is available as a bunch of 25 users. You can probably talk to sales for the possibility of getting a bunch with less than 25 users.

There are also Application server edition and unlimited editions which may be costlier than Enterprise edition.
CC1UXML 	IBM® DB2 Connect™ Application Server Edition - Activation 11.5 for Linux®, UNIX and Windows® 

CC1V0ML 	IBM® DB2 Connect™ Unlimited Edition for System z® - Activation 11.5 for Linux®, UNIX and Windows®

**Comment by imavo** [comment]
A salesperson will always try to upsell you...

If you are part of a large corporate, very carefully check whether or not there is an existing "Db2-connect gateway" deployed anywhere in your organization.   Some corporations have multiple of these. This "Db2-Connect server" can run on MS-Windows, Linux, AIX, or other platform.   It's important to know whether you already have Db2-connect servers deployed, because it's possible to __indirectly__ connect to Z/OS (or i )  via a Db2-connect gateway , and in this case, no additional license is required for python to connect. That's because the license is already paid via the cost of the Db2-connect server. Some configuration is required, but the basic idea is that from python you connect to the database "virtually hosted" on the Db2-connect server which in turn routes the connection to the target Z/OS subsystem. The same concept for Db2-for-i.

Sometimes, additional political persuasion is necessary to get the Db2-connect server configured to support your target subsystem (but in many cases the Db2-connect server is already suitably configured, it depends greatly on the complexity of your Z/OS estate).  So check first...

If your organization uses ILMT  (IBM's license management tooling), then its database will also record any Db2-connect servers that may be deployed, so it is often very useful to know the admins for the ILMT environment because they can tell you things that would otherwise remain hidden...

**Comment by blhack** [comment]
Thank you both.  Unfortunately it doesn't look like there is a db2 connect server deployed anywhere in the org.

@shilumathai okay, sounds like you're confirming what I suspect.  To be honest, coming from the non-IBM world, this was pretty foreign to me (you have to pay extra money to run a python script?!  WHAT!?!?)

I'm going to throw some extra information here that will hopefully get indexed by google and hopefully save some other people time in the future.

1) Contact IBM sales, and tell them that you need DB2 connect.  The most inexpensive option for this appears to be a package of 25 licenses.
2) If necessary, ask the sales person for a demo license.  If granted, they will provide you with a file named db2consv_t.lic
3) Copy this file to your linux machine and place it in the following directory:
     /usr/local/lib/python{version}/dist-packages/clidriver/license
(/usr/local/lib/python{version}/dist-packages/clidriver/ should have been created when you installed the python module. If it isn't found, try checking in other library directories on your system.  There should be a folder called "clidriver")
4) Run your python script (this may require elevated privileges, because it is going to generate a new file and place it in this clidriver/license directory the first time it is run)
5) At the end of the trial period, this license will expire and you will need to complete your purchase from IBM.

----

Hopefully those steps can be helpful to somebody else in the future!

**Comment by bimalkjha** [comment]
@blhack You need to pay extra money to connect to Db2 for z/OS or Db2 for iSeries using python script from non- z/OS and non- iSeries platform. If you connect to a Db2 server which is installed on Linux, Unix or Windows systems, no need to pay any money for connection using python! So, its the server which decides which client to allow the connection and which not! i.e. db2connect license requirement is enforced by server and not client.
So, you can connect to any db2 server installed on LUW platform using ibm_db free of cost. Hope it clarifies. Thanks.

**Comment by blhack** [comment]
hey @bimalkjha good clarification!  Yes, in my case I am connecting to db2 on iSeries.
