### ISSUE TITLE
Control which driver version is installed

### ISSUE THREAD

**Issue by sumedh10** [ibmdb/python-ibmdb#583]
Would it be possible to control the driver version that gets installed with the package? Looks like by default, the package always downloads the latest available version. 

I know the README talks about this in the [Environment Variables](https://github.com/ibmdb/python-ibmdb#envvar) section, but it assumes that the user either has an existing installation to which they can refer to or that they are willing to download the driver manually. But I was wondering if this can be handled in a programmatic way in this package.

**Comment by imavo** [comment]
The only way that I know to control the Db2-driver that gets installed is to __first__ install whatever compatible Db2-driver you need, then set & export the __IBM_DB_HOME__ environment variable appropriately for your specific driver.   Finally install the ibm_db module.    If you are using an IBM supplied Db2 driver then they support scripted (unattended) installation so depending on your scripting skills you could automate this.

Note that the ibm_db module will only download the latest clidriver if and only if the IBM_DB_HOME environment variable is not set.  But there's not currently a way to tell ibm_db which specific driver to download other than separate prior installation of the driver that you wish to u
se.

**Comment by sumedh10** [comment]
@imavo Thanks for the confirmation. 

> Note that the ibm_db module will only download the latest clidriver if and only if the IBM_DB_HOME environment variable is not set. 

Can we hack this by setting `IBM_DB_HOME` environment variable to some random value to ensure `ibm_db` doesn't download the latest driver? Or will it check that `IBM_DB_HOME` is set to a proper `clidriver` path? 

Our package requires `ibm_db` to connect to DB2 databases. So the next best thing I am hoping is that when a user downloads our custom package, we force `ibm_db` to _not_ download the latest `clidriver`, and instead let our custom package download the appropriate version.

**Comment by amukherjee28** [comment]
Hi @sumedh10 

Python ibm_db driver rely on clidriver for establishing the connection with the server. In any environment if the system is clean and no environment setting is applied (setting up the IBM_DB_HOME) then the installation of the ibm_db is followed by download of clidriver whose version is specific and we maintain the version.

In case the use has a specific need to use different driver we suggest the user to download the same and set the path using the IBM_DB_HOME environment variable prior to installation of ibm_db so that while ibm_db installation the download of the default clidriver is skipped.

The check for IBM_DB_HOME is just to see whether on not the variable is set or not. We do not validate the the nobility of the whats set inside the IBM_DB_HOME at installation time.

In case IBM_DB_HOME is set to some invalid path then error can be seen later while establishing connection. But your installation of ibm_db will go through.

In your particular case where you have a custom package that requires ibm_db not the clidriver you can have the value of IBM_DB_HOME set to some default location and then install ibm_db to by pass the clidriver download. But make sure before you attempt any connetion IBM_DB_HOME needs to be set to proper driver location in order to have a successful connection. The documentation of ibm_db will give you more details of this.

**Comment by sumedh10** [comment]
great, thank you.
