### ISSUE TITLE
ibm_db installation forcing download of aix64_odbc_cli

### ISSUE THREAD

**Issue by DarXzq2** [ibmdb/python-ibmdb#594]
Hello,
  pip installation of ibm-db is failing for us on CLI Driver - attempt to automatically  download  CLI driver ->  even though we specifically (  pip3.7 install -r requirements.txt  --no-index  –-find-links /home/my_environment/packages     )
)  encapsulate the package installation only to the local environment, thru the above parameters;   yet the install logic forcefully makes an external download call for CLI.

* Is it absolutely necessary to have CLI driver to accompany ibm-db ? ... if our python application does not make any remote db2 connections, all connections are localized to the database within a server,  so Db2 CLI driver will never be used anyway... 

* can ibm-db be installed without CLI/ODBC driver ?   
Thank you.

**Comment by imavo** [comment]
If you do not want to use clidriver   (because you instead have a pre-installed __different__ db2 driver) then you __must__ define environment variable IBM_DB_HOME before you run the `pip install`.  This is documented on the readme. It is the only known way to prevent the installer from attempting to download the clidriver.

After installation, to connect to a Db2 database with python, you need a Db2 driver, but it does not need to be clidriver, just some working Db2 driver for the CLI interface.

**Comment by bimalkjha** [comment]
@DarXzq2 If you have local Db2 server, server already has CLI/ODBC driver. So, no need to have different clidriver and as commented by imavo, ibm_db can be installed without CLI/ODBC driver.
Run `db2level` command on your system to know the install directory of db2 server. Then set system environment variable `IBM_DB_HOME=full/path/of/db2server/install/dir` and then run `pip install ibm_db`. In this case, ibm_db will use the CLI/ODBC driver that comes with server and avoid downloading of clidriver by itself. Thanks.
