### ISSUE TITLE
Exception: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.

### ISSUE THREAD

**Issue by jlestevezibm** [ibmdb/python-ibmdb#598]
Hi ,
I have a problem in Windows 10 updating my python version. With python 3.7 and ibmdb 3.0.1 it works fine but with pyhton 3.9.1 and ibmd-db 3.0.3 I get the reference error...

`Exception: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968`
i have a full installation of IBM dB2 10.5 configured and funcional 

```
db2licm -l

Nombre del producto:              "DB2 Connect Unlimited Advanced Edition for zSeries"
Tipo de licencia:                 "Dispositivo de cliente"
Fecha de caducidad:               "Permanente"
Identificador del producto:       "db2consv"
Información de versión:           "10.5"

````
i have test with python 3.9 and 3.8 and same problem ... 

EDIT 

I reinstall python 3.7 and ibm-db 3.0.3... installs and work fine without problem.... the insue is whith python >=3.8 

Regards

Josse

**Comment by amukherjee28** [comment]
Hi @jlestevezibm 

Can we narrow down your problem into two parts.

1. Are you facing the licensing issue with ibm_db version 3.0.3 with python version 3.8 and greater ?
2. For ibm_db version 3.0.1 is working fine for you for all of the python versions.
3. The db2 v10.5 which is installed and configured, is the same set as part of the IBM_DB_HOME environment variable.

Can you please confirm these points.

This will help to narrow down the issues.

**Comment by jlestevezibm** [comment]
Hi @amukherjee28 

Thanks for your response.

I have carefully repeated the installation.

windows10 
python 3.9.1
dn2 10.5 configured and IBM_DB_HOME enviroment variable sets correctly (C:\\ProgramData\\IBM\\DB2\\DB2COPY1).

1st test recived the error 
`FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'C:\\ProgramData\\IBM\\DB2\\DB2COPY1\\bin'`

I copied the content of last ntx64_odbc_cli.zip in my DB2COPY1 directory 

2nd test recived the error
`Exception: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968`

in pyhton 3.7 still works without problem 

Regards , thank in advance

Josse

**Comment by amukherjee28** [comment]
Hi Jose,

I see where the problem comes from.

So in windows when you install the driver there are two paths assigned.
1. The install location where the actual installation happens.
2. The install copy location where a copy is created during the installation process (default path C:\Program Data\IBM\DB2\<COPY_NAME>)

Now in IBM_DB_HOME environment variable you are suppose to set the INSTALL path location and not the COPY path location.

That explains the first error.

So what I would suggest here is can you unzip the ntx64_odbc_cli.zip into some folder and set the same path as part of the IBM_DB_HOME till clidriver.
Example if you unzip the ntx64_odbc_cli.zip into C:\ then set the IBM_DB_HOME=C:\ntx64_odbc_cli\clidriver.

You dont have to worry about the DB2COPY path.

Once you have the IBM_DB_HOME path set and proper license file copied you can install the ibm_db driver and try running the application again.

Thanks.

**Comment by jlestevezibm** [comment]
GREAT @amukherjee28 

I set my IBM_DB_HOME to "C:\Program Files\IBM\SQLLIB" reinstall ibm-db and WORKS!!!

Many thanks for your support

Josse

**Comment by jlestevezibm** [comment]
SOLVED . thank you
