### ISSUE TITLE
ERROR: Files/directories not found in /tmp/pip-install-y1nmuhp_/ibm-db/pip-egg-info

### ISSUE THREAD

**Issue by sahajoraj** [ibmdb/python-ibmdb#613]
I am pip installing IBM_DB in pivot cloud foundry under python 3.8.1 and getting the below error. 

ERROR: Files/directories not found in /tmp/pip-install-y1nmuhp_/ibm-db/pip-egg-info.
Note : I have set the environment variable IBM_DB_HOME : clidriver to force IBM_DB not to download cli driver.

If you anyone faced the similar issue.

**Comment by imavo** [comment]
Please specify the operating system (and distro name, and distro version) where python runs.

Please also verify you have the latest pip, by running `python -m pip install --upgrade pip` before you try installing ibm_db  .

**Comment by sahajoraj** [comment]
It is linux operating system (stack - cflinuxfs3) running in pcf and I am using python latest buildpack version 1.7.8 

python-3.7.6-linux-x64 and the pip that comes along with the python buildpack. I couldn't able to check the pip version in the buildpack.

**Comment by amukherjee28** [comment]
Hi @sahajoraj

You can get the pip version by running command pip --version or in some  cases pip3 --version.

The output of the command should also point out the site-packages directory path where the installation happens.

Could you please send the output of the commands.

Also can you send the complete error stack that you get while doing pip install.

That will help us to understand a bit more of what's going on.

Thanks

**Comment by sahajoraj** [comment]
PCF is using pip-pop version 0.1.4 for installation so I can't able to figure out which PIP version PIP-POP internally uses. 

Also after working with my PCF team we figured out there is no easy way to install CLI driver while staging in PCF where IBM_DB is expecting the driver. They have created a custom build by installing CLI driver to the python buildback and got it working.

just a thought, Is there any way can we force the IBM_DB not to look for CLI driver while staging (during PIP install) and actually look during execution. This way helps us to avoid the custom buildpack and use the standard buildpack provided by PCF.

**Comment by imavo** [comment]
The clidriver (on linux) is only a zipfile, and the clidriver is __optional__ only in the sense that any other Db2-driver with a CLI interface can be used instead of the tiny-footprint clidriver. (There are three other such CLI drivers available from IBM with different levels of functionality and different connectivity capabilities, and there are CLI drivers from non-IBM suppliers).

As per the ibm_db README , if you set the environment variable IBM_DB_HOME prior to running `pip install ibm_db` then the ibm_db setup will __not__ attempt to download or install a clidriver.  

You can install the clidriver yourself (or any compatible Db2-clidriver from IBM or other supplier) either BEFORE or AFTER you run the `pip install ibm_db`  as long as the IBM_DB_HOME environment variable is exported with a nonblank value (typically the value is the fully qualified path to the directory that contains the Db2-client).

However, although you can `pip install ibm_db` without automatically pulling in the clidriver, you will not be able to utilize the ibm_db module to connect, until and unless a compatible CLI driver is installed and configured.

The current builds of the python ibm_db module do not contain logic to install a CLI driver __after__ installation, but you can do this manually either before or after ibm_db gets installed . 

As mentioned, the tiny footprint clidriver is only a zipfile for Linux that needs to be unpacked.  Configuration is a separate matter, and that can be done   creating text/XML config files, either via scripting or other means.

**Comment by amukherjee28** [comment]
Hi @sahajoraj 

Can this issue be closed, as very detailed explanation was provided?

Please do let us know.
