### ISSUE TITLE
Issuing RUNSTAT and REORG

### ISSUE THREAD

**Issue by ram-ibm** [ibmdb/python-ibmdb#614]
Did find others in the same boat (wanting to run REORG/RUNSTAT using ibm_db) when searching the web - hoping to get a bit more clarity on how to get back responses please.

I got it to work with a call like so (ibm_db.callproc would not work - atleast I could not figure out how to make it work):
```
stmt = ibm_db.exec_immediate(conn, "CALL SYSPROC.ADMIN_CMD('REORG INDEXES ALL FOR TABLE SYSIBM.SYSINDEXES ALLOW WRITE ACCESS')))
```
But I am not able to use the resulting stmt object to get data back from it. I get an exception like so:
```
ibm_db.fetch_tuple(stmt)
Exception: Column information cannot be retrieved:
```

Hoping to get any insights on how to evaluate return code/messages from executing the command please? Happy to explore alternatives to calling ADMIN_CMD as well. Thanks!

In case anyone is wondering, you cannot run "REORG INDEXES ALL FOR TABLE SYSIBM.SYSINDEXES ALLOW WRITE ACCESS" directly as it is not supported from CLI. See here:
https://www.ibm.com/support/pages/100-tech-tips-99-how-run-reorg-command-cli-application

EDIT - I am using ibm_db v3.0.3.

**Comment by imavo** [comment]
Please give the operating-system detail (where python runs), version/edition, distro etc.

It will execute the runstatats, using ibm_db.callproc, as long as you specify the arguments correctly.
But there seems to be an issue collecting the result-set.

Example:
`stmt = ibm_db.callproc(ibm_db_conn, 'SYSPROC.ADMIN_CMD', ('reorg indexes all for table sysibm.sysindexes allow write access',))`

Notice that the third argument must be a tuple.

But there may still be an issue with collecting the result-set (may get `Exception: Supplied statement object parameter is invalid` ), as I observe on linux x64 with ibm_db 3.0.3.

**Comment by ram-ibm** [comment]
I am developing my script on a Mac, and the target audience is any operating system variation that ibm_db supports. We will be running tests on Linux distro pretty soon.

Yup understood that there is no set of data to be returned like in regular DML command, but it would be nice to atleast provide some information that reorg was submitted and it is running in the background (typically the case of online reorg's) or it completed successfully.

Thank you for the details of how to make callproc work - did not realize that input tuple needed that dummy entry in there.

I was going to see if ibm_db.stmt_error() might have some information -- but defer to you as to what to expect please? Maybe if there is no exception I assume that all is well?

**Comment by imavo** [comment]
It seems that when there is no result-set the relevant fetch methods will throw this exception (Column information cannot be retrieved: ) because the code assumes that you know what you are doing, and therefore assumes that there is a result set to be consumed.

SO:  Either catch and swallow this specific exception thrown by the fetch* method, or change your code to not try to consume a non-existent resultset for the runstats in admin_cmd().

Note: if the runstats begins and then fails with some runtime error, then I would expect a different exception to be thrown by the callproc (and then your code should never run a fetch) . So you would need catch and handle exceptions from callproc as well (possibly with a different exception handling block).

**Comment by ram-ibm** [comment]
I am going to remove the fetch logic after runstat / reorg -- will let try-catch logic handle any ensuing exception, assuming that no exception means command ran successfully or was submitted for background execution successfully.

Can we expect some sort of support for a return mechanism in ibm_db for calls to admin_cmd procedure please? Seems like a regular DB2 functionality worth supporting. Perhaps there could be a ibm_db.admin_cmd function?

**Comment by imavo** [comment]
I think that if the called stored-procedure __does__ return a result-set, then it should just work already.
Will try with an admin_cmd that does return a result set.

**Comment by ram-ibm** [comment]
I just tried to figure out the C code - speculated that perhaps there needs some logic to atleast elegantly handle the aftermath of a admin_cmd() db2 command execution. Did not get very far.

Let me know what to expect - thanks.

**Comment by amukherjee28** [comment]
Hi @ram-ibm

I was going through the conversation and here my understanding is very much in line with what @imavo has suggested.

ibm_db.callproc return type is completely dependent on how the Procedure call ends. Either the procedure call ends with the return type or the procedure call ends without any return type.

Here the choice is left to the developer to handle the return statement as we are unaware of the outcome in most of the cases.

SAMPLE PROGRAM TO EXPLAIN WITH RETURN TYPE
-------------------------------------------------------------------

'''
import ibm_db

#creating connection

print("Creating connection.......")
conn_string = "connection string"
conn = ibm_db.connect(conn_string,"","")
if conn:
    print("Connection ...... [SUCCESS]")
else:
    print("Connection ...... [FAILURE]")

stmt,p1 = ibm_db.callproc(conn,'SYSPROC.ADMIN_CMD',('describe select * from emp',))

try:
    row = ibm_db.fetch_tuple(stmt)

    while(row):
        print(row)
        row = ibm_db.fetch_tuple(stmt)
except:
    print("No rows to fetch")
'''

OUTPUT
------------------------

'''
Creating connection.......
Connection ...... [SUCCESS]
(452, 'CHARACTER', 6, 0, 'EMPNO', 5, '', 0)
(448, 'VARCHAR', 12, 0, 'FIRSTNME', 8, '', 0)
(453, 'CHARACTER', 1, 0, 'MIDINIT', 7, '', 0)
(448, 'VARCHAR', 15, 0, 'LASTNAME', 8, '', 0)
(453, 'CHARACTER', 3, 0, 'WORKDEPT', 8, '', 0)
(453, 'CHARACTER', 4, 0, 'PHONENO', 7, '', 0)
(385, 'DATE', 10, 0, 'HIREDATE', 8, '', 0)
(453, 'CHARACTER', 8, 0, 'JOB', 3, '', 0)
(500, 'SMALLINT', 2, 0, 'EDLEVEL', 7, '', 0)
(453, 'CHARACTER', 1, 0, 'SEX', 3, '', 0)
(385, 'DATE', 10, 0, 'BIRTHDATE', 9, '', 0)
(485, 'DECIMAL', 9, 2, 'SALARY', 6, '', 0)
(485, 'DECIMAL', 9, 2, 'BONUS', 5, '', 0)
(485, 'DECIMAL', 9, 2, 'COMM', 4, '', 0)
'''

However the same program when changed the ibm_db.callproc to a different statement

'''
stmt,p1 = ibm_db.callproc(conn,'SYSPROC.ADMIN_CMD',('REORG INDEXES ALL FOR TABLE SYSIBM.SYSINDEXES ALLOW WRITE ACCESS',))
'''

'''
Creating connection.......
Connection ...... [SUCCESS]
No rows to fetch
'''

As we cannot control the outcome of the query it is best to handle in the program itself.

Coming to the second query

@ram-ibm when you ask us to have a new API ibm_db.admin_cmd what exactly do you have in mind.
Are you suggesting to have a separate function just handle admin_cmd calls when made.
This is something that can be explored.

Thanks.

**Comment by ram-ibm** [comment]
Thank you for the detailed response.

The code as you have presented has a blanket except block - meaning that ANY exception will default to a "No rows to fetch" message. There could be other exceptions when database stopped responding, network glitches, and so on. My current try - except block are to catch those kind of exceptions. I, dare say, that the `while(row)` logic should really evaluate to false when there are no rows and not require us to lean on the exception handling logic. Hence the ask to better handle the return logic for calls to procedures like ADMIN_CMD.

One option would be to have a dedicated function that you can control the return content when we want to use ADMIN_CMD. That would allow us to develop more resilient code where there is no return object that we need to loop over and exception handling does what it is supposed to. Just a suggestion that I hope you can consider.

**Comment by imavo** [comment]
I am a fan of exception handling, and will not trust production code that lacks competent exception handling and error checking.

Apart from that, I don't see a need for a specific API for admin_cmd(), as the existing callproc just works - when used correctly, although would be useful to have options for avoiding enforcing exception handling for some types of code.

I suggest an API for programmers to be able to safely (without getting an exception)  test an IBM_DBStatement object (as returned from callproc) , and return True/False to indicate whether or not there is a result-set.   If there is no result set, programmers can choose to not run any fetch method  risking exceptions.   Another alternative is that instead of returning True/False, it could return an int , with 0 meaning no result-sets, 1 meaning a single result-set exists, 2 meaning two result-sets exist (if that can be known in advance ), and negative number indicating some run time error such as bad arguments etc.

I would also be satisfied if the __existing__ API `ibm_db.next_result()` had optional semantics for "fetch first OR next result" (currently it is only specified for the second or subsequent result set). That method already returns False if there is no next result-set, but it would be useful if it could also return False if there is no result-set (zero result-sets).

**Comment by ram-ibm** [comment]
If it helps, there are other DB2 calls that return no result sets --  DDL statements would not return any result sets. So what you propose would help there as well.

If the command returns a success code or some additional message - why not pass that back? Here are some examples of what I mean (DDL being the first example):
```
$ db2 "alter table mytable drop primary key"
DB20000I  The SQL command completed successfully.

$ db2 REORG TABLE mytable INDEX myindex INPLACE ALLOW WRITE ACCESS
DB20000I  The REORG command completed successfully.
DB21024I  This command is asynchronous and may not be effective immediately.
```
I am especially interested in knowing the "DB21024I" code for my current work.

We do know that based on the command attempted that we will not get a result set back -- so having another method to evaluate success would certainly be worth it.
