### ISSUE TITLE
connect return SQL5048N error 

### ISSUE THREAD

**Issue by JefferyChiang** [ibmdb/python-ibmdb#646]
Run the ibm_db.connect return SQL5048N error.  The release level of the database client is not supported by the release level of the database server.

My DB2 version is DB2/6000 7.2.9. Google for a long time and still not resolve it.
Is there any possible solution?

**Comment by imavo** [comment]
If your Db2-server version is 7.2 then that is indeed historic.  

You might be the only person on the planet still using that Db2-version.  So the "error" is nothing to do with python or ibm_db. Instead the message is caused because you are trying a combination of versions that is "not supported".

As you can see from the explanation of that error code SQL5048N is this:

**_"Database clients can only access database servers with a release level
which is in the range of one level lower than the client to two levels
higher than the client."_**

You are probably using the default clidriver that gets installed by default with python ibm_db module, and currently that will be a version 11 (or 11.5) .  But your Db2-server is more than 2 levels older that your CLI driver.

Db2  v8.1, v8.2, v9.1, v9.5, V9.7, v10.1, v10.5, v11.1, v11.5 have all been released since your Db2 v7.x version.

You might try uninstalling clidriver, and then you would need to find and install and configure a Db2 CLI driver that is no newer than v9.7. This client may itself have dependencies on the operating-system on which you install it, in other words it may struggle with modern operating systems that did not exist when v9.7 was created.

Additionally , I do not know if the current python ibm_db module will even work with a Db2 v9.7 cli driver.  You may struggle to find such old versions unless your company has a good archive or unless you have good contacts.

So you are "on your own" maybe, and good luck trying to get anyone to support this combination in a formal manner!

The real question is:  how much is it worth to you, to get this combination working?

**Comment by amukherjee28** [comment]
The resolution was provided with proper explanation. Hence closing the issue.
