### ISSUE TITLE
SQLSTATE HY021

### ISSUE THREAD

**Issue by mahoneyl** [ibmdb/python-ibmdb#657]
Hi guys I'm trying to understand what this error is telling me a little better and hoping somebody here might be able shine some light on it.

I'm calling a python program in aix from a rpgle program in os/400 via QCMDEXC all on the same local system.

Periodically this program will crash and return an error in python with the following stdout information.

```
STDOUT                                                                                                                      
Traceback (most recent call last):                                                                                          
  File "/source/prod/xlsx/.venv/lib/python3.6/site-packages/ibm_db_dbi.py", line 720, in close                            
    return_value = ibm_db.close(self.conn_handler)                                                                          
Exception: Error occurred in SQL Call Level Interface SQLSTATE=HY021 SQLCODE=-99999                                         
                                                                                                                            
During handling of the above exception, another exception occurred:                                                         
                                                                                                                            
Traceback (most recent call last):                                                                                          
  File "/source/prod/xlsx/xlsx.py", line 70, in <module>                                                              
    main()                                                                                                                  
  File "/source/prod/xlsx/xlsx.py", line 66, in main                                                                  
    conn.close()                                                                                                            
  File "/source/prod/xlsx/.venv/lib/python3.6/site-packages/ibm_db_dbi.py", line 722, in close                            
    raise _get_exception(inst)                                                                                              
ibm_db_dbi.DatabaseError: ibm_db_dbi::DatabaseError: Error occurred in SQL Call Level Interface SQLSTATE=HY021 SQLCODE=-9999
```

When I googled around this online I found some articles from ODBC docs that says HY021 has something to do with Consistency Checks?

HY021 | Inconsistent descriptor information | The descriptor information checked during a consistency check was not consistent. For more information, see "Consistency Checks" in SQLSetDescField.

And if I read more about it here https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetdescrec-function?view=sql-server-ver15#consistency-checks

It seems like it is saying the descriptions on fields are not consistent? Directly in my python code I am only accessing two files with ibm_db_dbi. All of the fields are uniquely named and uniquely described so I am confused on how this could be happening? I do have files in the RPGLE's activation group that have the same field names and different descriptions across different files; however the error does not happen consistently. I would think if that would be the problem the program would crash every time.

Is there a way to turn off consistency checking, is that something I should even be considering? Or maybe I could just avoid calling db.close() entirely and leave the connection open? Would there be any harm in that? Does the connection close automatically when the job ends / activation group is destroyed? Do AIX programs called from OS/400 share the same activation group?

Has anybody ran into this before and could point me in a right direction for a solution.

Thanks

**Comment by imavo** [comment]
If the error happens periodically then only forensic problem determination by yourself can lead to a diagnosis. Carefully checking the timestamps of the symptom, with the timestamps of significant events both in the Db2-diagnostics and in the operating-system diagnostics can sometimes yield clues. If the symptom only happens in a single environment, but never in test or dev then some volumetric or config differences may trigger the cause. Only you have sufficient details on which to lead to a theory to disprove.

Sometimes a source-code review of your app can also help, check carefully every detail of how database connections get opened and closed, what assumptions are being made, whether any defensive code needs to be present to assert assumption validity etc.

But you could also check some basic eliminations: 

- do you have the most recent version of software components (to eliminate already fixed bugs in those components)?

- In particular the latest ibm_db, and the latest Db2-driver for your platform?

If you don't have the most recent versions, consider making a test environment on which to attempt to recreate the symptom.

A possibility is that the supplied argument to ibm_db.close() is invalid for some reason (e.g stack corruption due to some other as yet undetected problem), and that invalid information gets passed to the Db2-driver which rejects it. Another possibility is that at the time the Db2-driver get the close request that the Db2-server side has already closed the connection for some reason. 

If you know a combination of circumstances that triggers the symptom, then a CLI trace can be useful to show what is happening at Db2-driver level. Refer to your Db2-docs for details on enabling CLI trace. This CLI trace is __NOT__ useful if you do not know when the symptom can trigger, because the output can be extremely verbose for a long running app and may cycle. A CLI trace will show the calls being made by the ibm_db module into the Db2-driver, along with the return codes from these APIs.

**Comment by SabaKauser** [comment]
Hello @mahoneyl 
As the sqlstate description says, it is reported by the driver when the describe information is not consistent or incorrect. However, I do not see a reason why would this error out in close call. You should definitely get a trace (db2 trace) to dig this further.


db2trc exe is under adm folder of clidriver installation on aix.
db2trc on -t -f trc.dmp
`run your application`
db2trc off
db2trc flw -t trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files with us to assist you further.

from command line: 
db2cli validate -all
and provide output of above command.

db2support . -s
and share the db2support.zip generated under the folder from where you executed the command.

Thanks,
Saba.
