### ISSUE TITLE
Getting error when connecting using SSL signed certificates

### ISSUE THREAD

**Issue by anilreddy103** [ibmdb/python-ibmdb#675]
Hi Team,

I am trying to connect to db2 database using ibm_db module using SSL signed certificate.

But I am getting the below error.

```
$ python gacdw.py
Traceback (most recent call last):
  File "gacdw.py", line 24, in <module>
    conn = ibm_db.connect(conn_str,'','')
Exception: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "420", "*", "*".  SQLSTATE=08001 SQLCODE=-30081
```

Code:

```
# connect to GACDW db and create csv file here
gacdw_db2_host="ip"
gacdw_db2_port="port"
gacdw_db2_name="dbanme"
gacdw_db2_uid="userid"
gacdw_db2_pwd="password"
             
conn_str = 'DATABASE='+gacdw_db2_name+';HOSTNAME='+gacdw_db2_host+';PORT='+gacdw_db2_port+';PROTOCOL=TCPIP;UID='+gacdw_db2_uid+';PWD='+gacdw_db2_pwd+';SSLSERVERCERTIFICATE=/tmp/db.pem;SECURITY=SSL;       DRIVER={IBM DB2 ODBC DRIVER};'
conn = ibm_db.connect(conn_str,'','')
             
fetch_number_of_hosts = "FETCH FIRST 5 ROWS ONLY"
             
sql = "SELECT * FROM TABLE WHERE CLIENTNAME='"+org_code+"'" + fetch_number_of_hosts
stmt = ibm_db.exec_immediate(conn, sql)
row = ibm_db.fetch_both(stmt)
```

I googled, but could not find a solution.

Any help to torubleshoot the issue would be appreciated.

Regards,
Anil

**Comment by bimalkjha** [comment]
@anilreddy103 Your error says, server is returning protocol specific error 420. This error and its solution is documented here: https://www.ibm.com/support/pages/sql30081n-sqlccsslsocketsetup-protocol-specific-error-codes-420-error-when-enabling-tls-transport-layer-security-due-dia3604e

It seems certificate label is not set on server. While generating client certificate from GSKit, you have used a label; set the same label using below command on server:
`db2 update dbm cfg using SSL_SVR_LABEL <label>`
Hope it should resolve your issue. Thanks.

**Comment by anilreddy103** [comment]
Thanks for the help. Closing this issue.

**Comment by anilreddy103** [comment]
Sorry for reopening the issue. I do not have access to any db2 related commands, nor they are installed in our environment. We are just using the python script to connect to db2 database. It works fine with non-ssl db2 database. We are facing this issue only when ssl is enabled on db2 database. and SSL_SVR_LABEL is already set on server side which is confirmed by db2 admin. Can you please advise if anything else can be looked into?

**Comment by imavo** [comment]
The most likely cause of your symptom is that your configuration is incorrect or incomplete in some way. 

If you give details about your configuration, you will get more help.  Without details, your question may never get an answer. 

Please answer all questions below. Get help from others if needed.

(1) For your python script, what is the port-number being used in your python script gacdw.py when you try using the SSLServerCertificate?

(2) What is the version of python (you can tell this with a command like `python -V`) ?

(3) What is the version of the python ibm_db module?  ( output of  a command like `pip show ibm_db` ) ?

(3) What is the operating system and version/distro that runs python?  MacOS? Windows? Linux? (which distro/version)? AIX? other?

(4) Why do you specify `/tmp` as the directory that contains the certificate file as shown in your question? That directory may get emptied on reboot. Better to put the certificate file eleswhere for example in the home directory of the user running python.

(5)  What are the permissions on the certificate file (use the command `ls -l ` on the certificate file)?

(6) What is the output of the `db2level` command where python is running?
You write that you "do not have access to any db2 related commands", but this makes no sense, because the ibm_db module
automatically installs with clidriver which includes the command `db2level`. 
This db2level command is not on the PATH, but you can find its location via `pip show ibm_db` 
which shows you the "Location:" and in that location is a directory called "clidriver" and a subdirectory called "bin" which has the Db2 client executable files including `db2level`. 
When you run `db2level` it shows a few lines of text and you should copy/paste all those lines into your answer.

For example: in a virtualenv, `pip show ibm_db | grep "Location:` might show something like this below (your directories will differ ):
Location: /home/myuser/djenv2/lib/python3.8/site-packages
Then:
`cd /home/myuser/djenv2/lib/python3.8/site-packages/clidriver/bin`
`./db2level`


(7) Are you running python in a virtual-machine, or in a container. You need to give details if either are true.


(8) Ask your Db2 admin to tell you the output of these commands on the Db2-server that you are trying to reach (assuming your Db2-server runs on linux or unix or windows ):
- what is the value of `db2 get dbm cfg | grep SSL_VERSIONS`
- what is the output of the `db2level` command on the Db2 Server ?
- what is the output of the command `db2 get dbm cfg | grep SSL_SVR_LABEL`
- what is the output of the command `db2 get dbm cfg | grep SSL_CIPERSPECS`
- what is the SSL port number being used by the Db2-instance (via SSL_SVCENAME)
- when the python script attempts to connect to the database with SSL enabled, what are the ERROR entries that appear in the Db2-server `db2diag.log` or diagnostics file (there may be several of these, but need the full text of these errors).


(9) If your Db2-server does NOT run on linux/unix/windows, you need to tell us the details (which platform Z/OS, i-series, z/Linux) and version.
