### ISSUE TITLE
ibm_db.fetch_assoc() sometimes got "Fetch Failure:" without sql_state

### ISSUE THREAD

**Issue by shimac-jp** [ibmdb/python-ibmdb#702]
My web application gets records by using ibm_db.fetch_assoc() as follows.

It sometimes fails.
str(exception) shows only "Fetch Failure: ".  There was no other information.
ibm_db.stmt_error() shows nothing.

Once this error occurs, fetch never succeeds.
But, after the application restarts, fetch succeeds.

This tends to occur when executing SQL that retrieves a large number of rows (several hundred thousand or so).

Could you tell me what is causing this and how I can fix this?

```
stmt = ibm_db.exec_immediate(conn, sql)
data = []
dictionary = ibm_db.fetch_assoc(stmt)
while dictionary != False:
     data.append(dictionary)
    dictionary = ibm_db.fetch_assoc(stmt)
```

**version**
ibm_db: 3.1.0

**Comment by imavo** [comment]
Skilled problem determination required. Most likely this is an operational problem caused by the design of the python script.

What client-side problem determination have you done?  What is the client operating-system where python runs? How much RAM and paging-space have you got? Have you checked the client operating-system diagnostics/event-log/messages?

You need to discover why the fetch fails (typically this happens because the underlying cursor has become closed, either due to the something that happens on the client workstation side, or due to something that happened on the Db2-server side). For example, how many rows trigger the failure (add some debugging counters to your code), or how much RAM is consumed when the failure happens?

If you are fetching "several hundred thousand rows" then an obvious question is why?  Could it be that you are trying to process a result-set in python that should better be processed either in the Db2 engine , or via an alternative design instead (and thereby return a significantly smaller result set to python)?
