### ISSUE TITLE
SystemError: <built-in function connect> returned NULL without setting an errorBug Report

### ISSUE THREAD

**Issue by mrcool4** [ibmdb/python-ibmdb#775]
- Operating System Name:
- db2level output from clidriver if in use:
- Target Db2 Server Version:DB2 v11.1.4.4
- Python Version: 3.9.5
- ibm_db version: 3.1.2
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME:C:\Users\username\AppData\Local\Programs\Python\Python39\Lib\site-packages\clidriver
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
import ibm_db
conn_str="database=ddtest;hostname=hostname;port=50020;protocol=tcpip;uid=user;pwd=password;"
ibm_db_conn = ibm_db.connect(conn_str, '', '')
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

1. Run the above script
2.

Error: 
  ibm_db_conn = ibm_db.connect(conn_str, '', '')
SystemError: <built-in function connect> returned NULL without setting an error

**Comment by imavo** [comment]
There are several hits for this symptom on this forum, if you Search.
For example
https://github.com/ibmdb/python-ibmdb/issues/714

**Comment by Earammak** [comment]
@mrcool4 , You can refer the following similar issues. 
[#692 ]( https://github.com/ibmdb/python-ibmdb/issues/692) 
 https://github.com/ibmdb/python-ibmdb/issues/694 
https://github.com/ibmdb/python-ibmdb/issues/371

**Comment by mrcool4** [comment]
Hi, I have looked all those issues already but it didn't help. Is there an issue using the default cli driver that comes with ibm-db package? Do I have to install any client tools?

**Comment by mrcool4** [comment]
I am also randomly seeing the following error.
`[IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "6".`

**Comment by imavo** [comment]
No Db2 client tools are needed solely for python ibm_db apart from clidriver (or its equivalent, which can be pre-installed).  

Please answer all questions.

What is your windows build and edition.
Show the text output of the winver command. 

How are you running python? i.e. directly at the cmd.exe prompt, or via some other tool like pycharm or a notebook or other (give details).

What are your regional settings, language/locale? 
What is the output of the `chcp` command in the cmd.exe window before you run the python script?  

What value of DB2CODEPAGE variable have you tried to set, in the cmd.exe window, before you run your python script?

What is the full text output of `pip show ibm_db` on this workstaiton?

Do you have any other Db2 product installed on the windows workstation?

Show the plain text output of the `SET` command in the cmd.exe window before you run python (attach as text file).

**Comment by alessandroToninelli** [comment]
Me Too. This library not work. same error on connect Api and all of those issues not help

**Comment by Earammak** [comment]
Can you please share the trace file.
Find the below steps:
cd clidriver install path, found with pip show ibm_db in Location: field of its output.
cd clidriver\bin
db2trc on -f trc.dmp
--> now run your application
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share these files trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by imavo** [comment]
@alessandroToninelli , if you run python on Microsoft-Windows, please run the small script below and tell us the result (should be 4 lines of text, if it works successfully, otherwise will throw an exception):

```
import os
import winreg

print("Value of the DB2CODEPAGE environment variable is: " + str(os.getenv('DB2CODEPAGE', default=None)))

path_codepage = r'System\CurrentControlSet\Control\Nls\Codepage'

try:
   root = winreg.ConnectRegistry(None, winreg.HKEY_LOCAL_MACHINE)
   registry_handle1 = winreg.OpenKeyEx(root, path_codepage)
   acp_value, acp_type = winreg.QueryValueEx(registry_handle1, 'ACP')
   print("ACP: " + acp_value)
   
   maccp_value, maccp_type = winreg.QueryValueEx(registry_handle1, 'MACCP')
   print("MACCP: " + maccp_value)

   oemcp_value, oemcp_type = winreg.QueryValueEx(registry_handle1, 'OEMCP')

   print("OEMCP: " + oemcp_value)
   registry_handle1.Close()

except:
    print("Caught exception")
    raise

```

**Comment by Earammak** [comment]
@imavo  Find the below result for the mentioned script:
 Value of the DB2CODEPAGE environment variable is: 1208
 ACP: 1252
 MACCP: 10000
 OEMCP: 437

**Comment by imavo** [comment]
@Earammak the mentioned script needs to be run on an mswindows workstation that experiences the symptom "<built-in function connect> returned NULL without setting an errorBug Report" , but I do not know if that's the case for the report you gave.

Looking at the code in ibm_db.c the function _python_ibm_db_connect_helper is broken in the sense that if the very first call  (non mvs, non i5) to cli/odbc (usually SQLAllocHandle with SQL_HANDLE_ENV ) does not return success, then the code unconditionally runs SQLGetDiagRec() which will also fail in this specific circumstance leading to an immediate return without setting any python error (hence the resulting symptom). So there are two different issues. First problem is that the SQLAllocHandle(for HENV) is failing in specific circumstances , and that is outside the control of python ibm_db, and the second problem is that the python ibm_db code should only conditionally run SQLGetDiagRec() or at the least guarantee some meaningful python error gets set in the event that SQLGetDiagRec() does not return SQL_SUCCESS.  These are two separate problems, I suspect.

Regarding the root cause of (the first problem) i.e. the first call to SQLAllocHandle for HENV failing, I do not have access to the source code of the clidriver, so I cannot quickly debug. The causes of this failure are always related to configuration at client side , and this differs between MS-Windows and other platforms. In particular it is easy to reproduce the specific error if the three MS-Windows registry settings that I mention in the script are set to 65001 and at the same time the DB2CODEPAGE variable is not set. Immediately the first SQLAllocHandle() for HENV will fail, and python ibm_db will not set a python error. Simply ensuring that DB2CODEPAGE is set to 1208 resolves that problem.  But there are many other potential causes of configuration problems here depending on which Db2-client is being used (i.e. clidriver or fat client etc).

I suspect it would be helpful if the python ibm_db code always set a python error when SQLDiagRec() does not return SQL_SUCCESS, for example with some message to indicate that there is a configuration problem with the Db2 client that is being used.  In this case, the `db2cli` command should also fail but with a different error symptom for example SQL1007N etc.  The Db2 tracing on MS-Windows in this specific case is not so helpful, because it is the very first call to the odbc/cli that is failing (hence CLI trace is rather short). The clidriver should have some additional diagnostic capability to sanity check the environment when SQLAllocHandle() for HENV does not return success.

**Comment by Earammak** [comment]
@imavo , In my machine i do not see this issue actually. Since you have asked to share dv2codepagesettings, so i have shared it here. The script i have run it on windows machine only.

**Comment by Earammak** [comment]
And in my machine, Active code page : 437

**Comment by imavo** [comment]
@Earammak I addressed my suggestion to run the script to @alessandroToninelli because that person posted an update in this threading implying they get this symptom,  and the original poster @mrcool4 did not respond to requests for clarification. It is difficult to debug this without a workstation that experiences the symptom.

**Comment by Earammak** [comment]
@mrcool4 Can you please provide the update on this?
Thanks

**Comment by mrcool4** [comment]
Hi, 
I couldn't resolve this issue on Windows so moved onto Linux(WSL) and it worked.
