### ISSUE TITLE
ibm_db_dbi::ProgrammingError: SQLNumResultCols failed

### ISSUE THREAD

**Issue by ajlorido** [ibmdb/python-ibmdb#799]
Hello, we're having this problem while trying to get rows from the db2. 
We're using flask + sqlalchemy orm in our app that works fine with Oracle connection but it breaks while trying to get the same result with db2.
I know there's another thread with this issue but there is not a solution published, that's why i create a new one.

.**........\lib\site-packages\ibm_db_dbi.py", line 1290, in _set_cursor_helper
    raise self.messages[len(self.messages) - 1]
ibm_db_dbi.ProgrammingError: ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0245N  The invocation of routine "COUNT" is ambiguous. The argument in position "1" does not have a best fit.  SQLSTATE=428F5\r SQLCODE=-245**

- Operating System Name: **Windows 10**
- db2level output from clidriver if in use:
**DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11056" with level identifier "0607010F".
Informational tokens are "DB2 v11.5.6000.7091", "special_13806",
"DYN2201171140WIN64_13806", and Fix Pack "0".
Product is installed at "C:\work\ntx64_odbc_cli\clidriver" with DB2 Copy Name
"IBM Data Server Driver For ODBC and CLI".**
- Target Db2 Server Version:
- Python Version:3. 10
- ibm_db version: 
- ibm-db                      3.1.1
- ibm-db-alembic              0.2.0
- ibm-db-sa                   0.3.8

**Comment by Earammak** [comment]
@ajlorido  Can you please check for the below update which is mentioned in [https://github.com/ibmdb/python-ibmdb/issues/590](url)
Please find the db2level command and report its output.
Next, in your python code, if you are using a parameter-marker in the query (i.e. using ?), then a value needs to be bound for that parameter-marker at runtime. The actual value must be valid. The value can be a literal like '1', or *, otherwise it must be a column-name in the table or in the result-set. If no value is bound for this parameter-marker, then Db2 will throw an exception -245 sqlcode. If you only want to count the rows , then you can use select count(1) from auction.auction_lot_oubound.

**Comment by ajlorido** [comment]
Hello Earammak, thanks for your reply.
I've tried to the link you provided but no result there, maybe it was deleted? Can you check it?
Regarding the '1' or '*' I thought about it, but since the flask-admin worked fine with Oracle I supposed it will also work fine with DB2, i will check it.
Thanks
