### ISSUE TITLE
logging the bad entries along with error messages

### ISSUE THREAD

**Issue by pavan879** [ibmdb/python-ibmdb#816]
https://github.com/ibmdb/python-ibmdb/blob/3cce6b3b10a6b704c5103b3d27964bc1b56db630/IBM_DB/ibm_db/ibm_db_tests/test_execute_many.py#L60

wanted to print/log the bad source entries along with the error message, could anyone provide thoughts on this.
example-
input used from above link (line 60)-
((50, 'Hanes', False), (55, 'Mike', False, 'Extra'), (55.5, 'invalid row','not a bool'), (60, 'Quigley'), (70, None, None), [75, 'List', True] )

how we can log the bad entry along with error message-
**_bad record: (55, 'Mike', False, 'Extra')
Error 1: Value parameter tuple 2 has more parameters than previous tuple_**

**Comment by Earammak** [comment]
@pavan879,
The error message we are getting is an expected behaviour and it is mentioned in the script.
That error message is correct and test case will be passed [ it's a negative test case].

If you really want to see the respective errors in console, you can write one sample script with the same data and try.
You should be able to see the error message.

I tried with the same sample script and output is:
4
10, Sanders, True
20, Pernal, False
30, Marenghi, True
40, OBrien, False
Error 1: Value parameter tuple 2 has more parameters than previous tuple
Error 2: Value parameter tuple 3 has types that are not homogeneous with previous tuple
Error 3: Value parameter tuple 4 has fewer parameters than previous tuple
Error 4: Value parameter 6 is not a tuple
2

Thanks
