### ISSUE TITLE
Exception: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004  SQLCODE=-1042 [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004  SQLCODE=-1042

### ISSUE THREAD

**Issue by ritikakat** [ibmdb/python-ibmdb#868]
I tried to add this path for my system "c:\python\lib\site-packages\clidriver\bin\amd64.VC12.CRT" in the system and env variables path but still getting the same error. This was the only verified solution pasted in stack overflow but it did not work for me.

- Operating System Name: windows 10
- Python Version: 3.8.16
- ibm_db version: 3.1.3

- Test script to reproduce the problem. - db2_instance=ibm_db.connect(connection_string,'','')

  def __init__(self, config_data):

        self.logger = logging.getLogger('nlp')        
        if not os.path.exists(config_data['db2_config_path']):
            raise Exception("401 ->>- IBM DB2 config file is not found at "+str(config_data['db2_config_path']))    
        self.db2_config = {}
        
        with open(config_data['db2_config_path'],'r',encoding='utf-8') as f:
            self.db2_config = json.load(f)
            f.close()
        
        database = self.db2_config['connection']['db2']['database']
        hostname = self.db2_config['connection']['db2']['hosts'][0]['hostname']
        port = str(self.db2_config['connection']['db2']['hosts'][0]['port'])
        username = self.db2_config['connection']['db2']['authentication']['username']
        password = self.db2_config['connection']['db2']['authentication']['password']
        driver = str('{IBM DB2 ODBC DRIVER}')        
        connection_string = "DRIVER=" +driver+ ";DATABASE=" +database+ ";HOSTNAME=" +hostname+ ";PORT=" +port+ ";PROTOCOL=TCPIP;SECURITY=SSL;SSLSererCertificate=DigiCertGlobalRootCA.crt;UID=" +username+ ";PWD=" +password
        try: 
            
            self.db2_instance=ibm_db.connect(connection_string,'','')
            print("here")
            self.db2_conn = dbi.connect(connection_string)
            self.logger.info(f"Connected to ibm db2")
            print("successful")
        except Exception as ex:
            self.logger.debug(ibm_db.conn_errormsg())
            raise Exception(ex)

**Comment by imavo** [comment]
There can be more than one cause of the -1042 sqlcode. When reported by the client side, it's almost always an environmental/configuration cause.


Your question includes this: `"SSLSererCertificate=DigiCertGlobalRootCA.crt"`

Should be:
`"SSLServerCertificate=DigiCertGlobalRootCA.crt"`

You may have other problems as well.

You can manually create+configure the db2dsdriver.cfg (xml file) with your DSN details and then use the db2cli tool to validate the db2dsdriver.cfg, and then use the db2cli tool to verify that the connection is working.  The advantage of doing this is that it eliminates python temporarily, in other words, if you can get a working connection with db2cli, then your connection from Python will also succeed (otherwise it's YOUR mistake). 

Study the Db2-LUW online knowledge centre for details of how to create+configure your db2dsdriver file and how to test connections with the db2cli tool.

**Comment by ritikakat** [comment]
I went through the documentation. Tried to manually configure the cfg and ini driver files. These are the results from the validation. Also I did complete reinstallation of python to prevent any misconfiguration. Now I am using ibm-db 3.1.3 and python 3.10.9.

===============================================================================
Client information for the current copy (copy name: C_Users_09698G744_Downloads_ntx64_odbc_cli_clidriver):
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.5.8000.3209 (special_26260/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : C:\Users\09698G744\Downloads\ntx64_odbc_cli\clidriver

Common App Data Path      : C:\ProgramData\IBM\DB2\C_Users_09698G744_Downloads_ntx64_odbc_cli_clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\db2diag.log

===============================================================================
List of all IBM Data Server client packages on the current workstation:
===============================================================================

Copyname                                                Version Package Language Installed-Location
-------------------------------------------------------------------------------
C_Users_09698G744_Downloads_ntx64_odbc_cli_clidriver[C] 11.5.0800 CLI     EN       C:\Users\09698G744\Downloads\ntx64_odbc_cli\clidriver
-------------------------------------------------------------------------------
 CLI: IBM Data Server Driver for ODBC and CLI
-------------------------------------------------------------------------------

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Success: The system db2dsdriver.cfg schema validation completed successfully without any errors.

===============================================================================
db2cli.ini validation for data source name "bludb":
===============================================================================

[ Keywords used for the connection ]

Keyword                   Value
---------------------------------------------------------------------------
DATABASE                  bludb
HOSTNAME                  "6bfcd44f-3a92-4d09-b401-897c5f9b320d.bs2ipa7w0uv9tsomi9ig.databases.appdomain.cloud"
PORT                      31810
PROTOCOL                  TCPIP
UID                       "ec515a50"
PWD                       ******************
QUERYTIMEOUT              0
QUERYOPTIMIZE             **UNKNOWN**

===============================================================================
db2dsdriver.cfg validation for data source name "bludb":
===============================================================================
description : "alias1_description"
===============================================================================

Keywords                  Valid For     Value
---------------------------------------------------------------------------
GlobalParam               **UNKNOWN**

===============================================================================
The validation is completed.
===============================================================================


Can you point out which file has the error because I am still stuck at the same error wrt connection.
Exception: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004  SQLCODE=-1042


        self.logger = logging.getLogger('nlp')
        if not os.path.exists(config_data['db2_config_path']):
            raise Exception("401 ->>- IBM DB2 config file is not found at "+str(config_data['db2_config_path']))    
        self.db2_config = {}
        with open(config_data['db2_config_path'],'r',encoding='utf-8') as f:
            self.db2_config = json.load(f)
            f.close()
        database = self.db2_config['connection']['db2']['database']
        hostname = self.db2_config['connection']['db2']['hosts'][0]['hostname']
        port = str(self.db2_config['connection']['db2']['hosts'][0]['port'])
        username = self.db2_config['connection']['db2']['authentication']['username']
        password = self.db2_config['connection']['db2']['authentication']['password']
        driver = str('{IBM DB2 ODBC DRIVER}')
        
        connection_string = "DRIVER=" +driver+ ";DATABASE=" +database+ ";HOSTNAME=" +hostname+ ";PORT=" +port+ ";PROTOCOL=TCPIP;SECURITY=SSL;SSLServerCertificate=DigiCertGlobalRootCA.crt;UID=" +username+ ";PWD=" +password
        try: 
            self.db2_instance=ibm_db.connect(connection_string,'','')
            self.db2_conn = dbi.connect(connection_string)
            self.logger.info(f"Connected to ibm db2")
        except Exception as ex:
            self.logger.debug(ibm_db.conn_errormsg())
            raise Exception(ex)

**Comment by imavo** [comment]
Avoid using both db2cli.ini and db2dsdriver.cfg, use only one of these, preferably the latter.
After successful validation, be sure to run the `-connect` option.

The ssl server certificate must appear in the db2dsdriver.cfg as a parameter for the database and/or dsn , along with any other options that are required.

Here is a partial example (redacted)

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<configuration>
  <databases>

    <database host="....bluemix.net" name="bludb" port="50001" > 
      <parameter name="SecurityTransportMode" value="SSL" />
      <parameter name="SSLServerCertificate" value="/home/db2inst9/DigiCertGlobalRootCA.crt" />
    </database>

  </databases>

  <dsncollection>
    <dsn alias="cloud1" host="....bluemix.net" name="bludb" port="50000" > </dsn>

    <dsn alias="cloud2" host=".....bluemix.net" name="bludb" port="50001" > 
      <parameter name="SecurityTransportMode" value="SSL" />
      <parameter name="SSLServerCertificate" value="/home/db2inst9/DigiCertGlobalRootCA.crt" />
    </dsn>
  </dsncollection>

</configuration>
```

**Comment by ritikakat** [comment]
I have updated the configuration file as you suggested. Also, I am only using the db2dsdriver.cfg now.
Validate is completed successfully using it. Connection, however, failed with the same error. [FAILED]: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

C:\ProgramData\IBM\DB2\C_Users_09698G744_AppData_Local_anaconda3_lib_site-packages_clidriver\cfg>db2cli validate -dsn "bludb" -user "..." -passwd "..." -connect

===============================================================================
Client information for the current copy (copy name: C_Users_09698G744_Downloads_ntx64_odbc_cli_clidriver):
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.5.8000.3209 (special_26260/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : C:\Users\09698G744\Downloads\ntx64_odbc_cli\clidriver

Common App Data Path      : C:\ProgramData\IBM\DB2\C_Users_09698G744_Downloads_ntx64_odbc_cli_clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\db2diag.log

===============================================================================
List of all IBM Data Server client packages on the current workstation:
===============================================================================

Copyname                                                Version Package Language Installed-Location
-------------------------------------------------------------------------------
C_Users_09698G744_Downloads_ntx64_odbc_cli_clidriver[C] 11.5.0800 CLI     EN       C:\Users\09698G744\Downloads\ntx64_odbc_cli\clidriver
-------------------------------------------------------------------------------
 CLI: IBM Data Server Driver for ODBC and CLI
-------------------------------------------------------------------------------

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Success: The system db2dsdriver.cfg schema validation completed successfully without any errors.

===============================================================================
db2cli.ini validation for data source name "bludb":
===============================================================================

[ Keywords used for the connection ]

Keyword                   Value
---------------------------------------------------------------------------
DATABASE                  bludb
HOSTNAME                  "6bfcd44f-3a92-4d09-b401-897c5f9b320d.bs2ipa7w0uv9tsomi9ig.databases.appdomain.cloud"
PORT                      31810
PROTOCOL                  TCPIP
UID                       "ec515a50"
PWD                       ******************
QUERYTIMEOUT              0
QUERYOPTIMIZE             **UNKNOWN**

===============================================================================
db2dsdriver.cfg validation for data source name "bludb":
===============================================================================
description : "alias1_description"
===============================================================================

Keywords                  Valid For     Value
---------------------------------------------------------------------------
GlobalParam               **UNKNOWN**

===============================================================================
Connection attempt for data source name "bludb":
===============================================================================

[FAILED]: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004


===============================================================================
Error: The validation operation failed.
===============================================================================

===============================================================================
The validation is completed.
===============================================================================

**Comment by imavo** [comment]
The validation report shows that your db2cli.ini still exists (and shows its contents) which contradicts what you wrote above, I suggest you erase that file or move it to somewhere impossible for db2cli to find. Your `db2cli validate` should report that it cannot find db2cli.ini (which is an acceptable error) and that it CAN find and successfully validate the db2dsdriver.cfg.

Next, as you can now see, your `db2cli validate -connect ....` is reporting the -1042. 

This proves that the problem is nothing to do with python (because db2cli does not use Python in any way), as db2cli is written in c and c++ . Python uses db2cli , but not the other way around.

You wrote (but you gave no evidence) that you adjusted the system PATH to include the correct VC12.CRT subdirectory.

Now verify that, carefully.

Just before you run the `db2cli validate -connect .....` , use `echo %PATH%` and save it to a file , and put it in  your reply to this message.

You want to ensure that __EITHER__ the two vc12 c-runtime DLLs are already present in a directory that is provably on the PATH, __OR__ copy the 2 dll files into a directory that is always guaranteed to be on the PATH .
When both of those DLL files cannot be loaded, that is the cause of 90% of client side -1024 sqlcodes (but other causes can exist). 

Other causes: In particular if your workstation has any __other___ copies of either db2cli or any IBM supplied client sideDb2  odbc driver, or any IBM GSK component,  that is present on the PATH - this can introduce DLL hell situations that can only be resolved by either uninstallation of old packages, or by careful removal of such unintented directories from any PATH (either the system PATH or the user PATH, or both) so as to ensure that only a single db2cli and GSK set of libraries are accessible on the PATH at the time you run your python code (or db2cli code).

Next, if you have double checked this, and found no problems, check for any additional information in the client side db2diag.log file. You may need to search the filesystem to find the file, and verify it has the correct date to match the time when you run the `db2cli validate -connect ...` step.

If you find no interesting messages in the db2diag.log, the next step would be to install the Microsoft procmon tool, available from their website, and use that to filter any unsuccessful system calls from db2cli.exe whe you are running the `db2cli validate -connect` step. That usually solves all remaining problems by exposing the failing system call which you should then be able to investiigate.

**Comment by ritikakat** [comment]
This is the content of my db2cli.cfg file:-
[Common]
QueryTimeout=0
QueryOptimize=5
[bluedb]
Database="bludb"
Hostname="db2w-jofzetd.us-south.db2w.cloud.ibm.com"
Port=50001
Protocol=TCPIP
UID="..."
PWD="..."

This is the content of db2dsdriver.cfg file :-- attched for reference
[db2dsdriver_content.txt](https://github.com/ibmdb/python-ibmdb/files/11998238/db2dsdriver_content.txt)


Output of validation - (after removing ini)

C:\ProgramData\IBM\DB2\C_Users_09698G744_AppData_Local_anaconda3_lib_site-packages_clidriver>db2cli validate -dsn "cloud1" -user "..." -passwd "..." -connect

===============================================================================
Client information for the current copy (copy name: C_Users_09698G744_AppData_Local_anaconda3_Lib_site-packages_clidriver):
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.5.6000.7091 (special_13806/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : C:\Users\09698G744\AppData\Local\anaconda3\Lib\site-packages\clidriver

Common App Data Path      : C:\ProgramData\IBM\DB2\C_Users_09698G744_AppData_Local_anaconda3_Lib_site-packages_clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\db2diag.log

===============================================================================
List of all IBM Data Server client packages on the current workstation:
===============================================================================

Copyname                                                                 Version Package Language Installed-Location
-------------------------------------------------------------------------------
C_Users_09698G744_AppData_Local_anaconda3_Lib_site-packages_clidriver[C] 11.5.0600 CLI     EN       C:\Users\09698G744\AppData\Local\anaconda3\Lib\site-packages\clidriver
-------------------------------------------------------------------------------
 CLI: IBM Data Server Driver for ODBC and CLI
-------------------------------------------------------------------------------

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Success: The system db2dsdriver.cfg schema validation completed successfully without any errors.

===============================================================================
db2cli.ini validation for data source name "cloud1":
===============================================================================

Note: The validation utility could not find the configuration file db2cli.ini.
The file is searched at
"C:\ProgramData\IBM\DB2\C_Users_09698G744_AppData_Local_anaconda3_Lib_site-packages_clidriver\cfg\db2cli.ini".

===============================================================================
db2dsdriver.cfg validation for data source name "cloud1":
===============================================================================

[ Parameters used for the connection ]

Keywords                  Valid For     Value
---------------------------------------------------------------------------
DATABASE                  CLI,.NET,ESQL bludb
HOSTNAME                  CLI,.NET,ESQL db2w-jofzetd.us-south.db2w.cloud.ibm.com
PORT                      CLI,.NET,ESQL 50001
UID                       CLI           **DUPLICATE**
PWD                       CLI           **DUPLICATE**
SECURITYTRANSPORTMODE     CLI,.NET,ESQL **DUPLICATE**
SSLSERVERCERTIFICATE      CLI,.NET,ESQL **DUPLICATE**

===============================================================================
Connection attempt for data source name "cloud1":
===============================================================================

[FAILED]: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004


===============================================================================
Error: The validation operation failed.
===============================================================================

===============================================================================
The validation is completed.
===============================================================================

echo %PATH% output - 

C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;c:\users\09698g744\appdata\local\anaconda3\lib\site-packages;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\09698G744\AppData\Local\anaconda3\Lib\site-packages\clidriver\bin\amd64.VC12.CRT;C:\Users\09698G744\AppData\Local\anaconda3\Library\bin;C:\Users\09698G744\AppData\Local\anaconda3;C:\Users\09698G744\AppData\Local\anaconda3\Library\usr\bin;C:\Users\09698G744\AppData\Local\anaconda3\Library\mingw-w64\bin;C:\Users\09698G744\AppData\Local\anaconda3\Scripts;C:\ProgramData\IBM\DB2\C_Users_09698G744_AppData_Local_anaconda3_lib_site-packages_clidriver\cfg;C:\Users\09698G744\AppData\Local\anaconda3\Lib\site-packages\clidriver\bin;C:\Users\09698G744\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\09698G744\AppData\Local\Programs\Python\Python39\;C:\Users\09698g744\anaconda3\envs\ethics\lib\site-packages\;C:\Users\09698G744\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\09698G744\AppData\Local\Programs\Python\Python311\;C:\Users\09698G744\AppData\Local\Microsoft\WindowsApps;C:\Users\09698G744\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\09698G744\AppData\Roaming\npm;C:\supply_sust_proj\openshift-origin-client-tools-v3.10.0-dd10d17-windows\;C:\supply_sust_proj\openshift-origin-client-tools-v3.10.0-dd10d17-windows\oc.exe;C:\Users\09698G744\AppData\Local\anaconda3\Lib\site-packages\clidriver\bin\amd64.VC12.CRT;C:\Users\09698G744\AppData\Local\Microsoft\WindowsApps\python.exe;C:\\Users\\09698G744\\AppData\\Roaming\\nltk_data;C:\Users\09698G744\Anaconda3\Lib\site-packages\en_core_web_sm\;C:\ProgramData\IBM\DB2\C_Users_09698G744_AppData_Local_anaconda3_lib_site-packages_clidriver\cfg;


This path C:\Users\09698G744\AppData\Local\anaconda3\Lib\site-packages\clidriver\bin\amd64.VC12.CRT has runtime dlls
msvcp120.dll and msvsr120.dll
C:\Users\09698G744\AppData\Local\anaconda3\Lib\site-packages\clidriver\bin this folder has the db2cli application that I am running. 

I dont find these dlls anywhere else. I found one in downloads folder so I removed the Downloads folder from system path and also deleted the old files.
![image](https://github.com/ibmdb/python-ibmdb/assets/138959258/fa0a3c01-32bf-4e0d-83ca-f4b455b24246)

**Comment by imavo** [comment]
I forgot to ask if you already tested the `db2cli validate -connect ....` when running in an elevated cmd window (i.e. as administrator).
That is sometimes important, especially if you are in a corporate environment with restrictions on the file system that are different from windows defaults.
So please report on that.

Next, your PATH has more than 1800 bytes, verify registry setting `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled`  has value 1  to enable long paths.


Clean up your PATH as follows:

(1) It is unwise to have duplicates on your PATH, and you seem to have at least two duplicates:
C:\ProgramData\IBM\DB2\C_Users_09698G744_AppData_Local_anaconda3_lib_site-packages_clidriver\cfg
C:\Users\09698G744\AppData\Local\anaconda3\Lib\site-packages\clidriver\bin\amd64.VC12.CRT
Remove dups, and move the ...amd64.VC12.CRT to the start of the PATH (i.e make it the first entry).
Note: I'm assuming you are using the 64-bit python and 64-bit db2cli, because you mention amd64.VC12.CRT
(i.e. if you are using a 32-bit version of python/db2cli, then amd64.VC12.CRT is not relevant).

(2) You should have only 1 version of Python (and subdirs) on your PATH, but yours shows possibly three:
C:\Users\09698G744\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\09698G744\AppData\Local\Programs\Python\Python311;
C:\Users\09698G744\AppData\Local\Programs\Python\Python311\Scripts;
C:\Users\09698G744\AppData\Local\Programs\Python\Python39;
C:\Users\09698G744\AppData\Local\Programs\Python\Python39\Scripts;
Choose only one version, remove entries relating to the others. Reboot afterwards, then again verify the PATH only has a single version of Python.


When searching file systems, it's better to open an elevated cmd window, running as admistrator, and use "cd /d c:\" followed by "dir /a /s "(followed by the search-argument). Searching in the GUI without being admin exhibits different behaviour, in my experience. If you do not have local administrator rights on your workstation, then searches are limited in scope anyway.


Please check also the client-side db2diag.log as mentioned.

Also follow up with procmon to see what db2cli is doing under the covers.

**Comment by ritikakat** [comment]
Did all of the above steps you mentioned. Tried administrator mode, cleaned the paths, modified registry settings, checked the versions then I was finally able to connect.
Thanks a lot for your help!! @imavo  
Closing the ticket as the issue is resolved.
