### ISSUE TITLE
Issue when downloading ibm_db package in docker

### ISSUE THREAD

**Issue by surya18091997** [ibmdb/python-ibmdb#892]
FROM python:3.8-slim

ENV IBM_DB_HOME /etc/ld.so.conf.d/clidriver

RUN apt-get update && apt-get install -y \
       wget \
       tar \
       gcc \
       libc-dev \
       libaio1 \
       libaio-dev \
       && rm -rf /var/lib/apt/lists/*

RUN wget https://our-url/linuxx64_odbc_cli.tar.gz
RUN tar -xf linuxx64_odbc_cli.tar.gz
RUN mv clidriver /etc/ld.so.conf.d/
RUN echo /etc/ld.so.conf.d/clidriver/lib > /etc/ld.so.conf.d/db2.conf
RUN ldconfig

COPY requirements.txt .

RUN pip install -r ibm_db

I am getting gcc -pthread -shared build/temp.linux-aarch64-cpython-311/ibm_db.o -L/etc/ld.so.conf.d/clidriver/lib -L/usr/local/lib -ldb2 -o build/lib.linux-aarch64-cpython-311/ibm_db.cpython-311-aarch64-linux-gnu.so
172.7       /usr/bin/ld: skipping incompatible /etc/ld.so.conf.d/clidriver/lib/libdb2.so when searching for -ldb2
172.7       /usr/bin/ld: cannot find -ldb2
172.7       /usr/bin/ld: skipping incompatible /etc/ld.so.conf.d/clidriver/lib/libdb2.so when searching for -ldb2
172.7       collect2: error: ld returned 1 exit status
172.7       error: command '/usr/bin/gcc' failed with exit code 1
172.7       [end of output]
172.7
172.7   note: This error originates from a subprocess, and is likely not a problem with pip.
172.7   ERROR: Failed building wheel for ibm_db
172.7 Failed to build ibm_db
172.7 ERROR: Could not build wheels for ibm_db, which is required to install pyproject.toml-based projects
172.7
172.7 [notice] A new release of pip available: 22.3.1 -> 23.2.1
172.7 [notice] To update, run: pip install --upgrade pip

Help me in resolving this , i ran file libdb2.so

libdb2.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked

**Comment by bimalkjha** [comment]
@surya18091997 I am not sure on which Operating System you are trying to install ibm_db and of what version. You have not shared all info requested in new issue template. Please share output of `uname -a` command and complete output of `pip install ibm_db` without omitting any line.

In the shared error, this error seems the root cause: `172.7 /usr/bin/ld: skipping incompatible /etc/ld.so.conf.d/clidriver/lib/libdb2.so when searching for -ldb2`
If libdb2.so is incompatible then you are trying to install on different platform. Under clidriver/lib, libdb2.so is a softlink for libdb2.so.1 file. i.e. actual file is libdb2.so.1 not libdb2.so. Better you download clidriver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz and then try. Please run below commands and share complete output:
```
cd /etc/ld.so.conf.d/clidriver/lib/
uname
uname -m
file *
```
Thanks.

**Comment by surya18091997** [comment]
@bimalkjha - I am not aware that the architecture of the docker image is based on the host machine , so in my case since i have m1 machine my docker machine architecture was aarch64 . So the skipping incompatible issue occurred . 

Later i specified my docker base image to be amd64 , which worked.

FROM --platform=linux/amd64 python:3.8-slim

DISCLAIMER - The image may run into some issues due to emulations .

Thanks .
