### ISSUE TITLE
Connection to DB2 fails for IPv6 address in db2dsdriver.cfg file

### ISSUE THREAD

**Issue by sudhakar8488** [ibmdb/python-ibmdb#922]
- Operating System Name:
- db2level output from clidriver if in use:
- Target Db2 Server Version: DB2 11.5
- Python Version: 3.11
- ibm_db version: 3.2.2
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
- DB2DSDRIVER_CFG_PATH=/opt/ibm/db2/clidriver/cfg
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:
[db2testfiles.zip](https://github.com/ibmdb/python-ibmdb/files/14579881/db2testfiles.zip)

------------------
Running test
------------------

1) test without use of "db2dsdriver.cfg" :
python3 db2_conn_ssl.py

-- RESULT:
connection successful

2) test connection with DSN with IPv6 address

   a) set DB2DSDRIVER_CFG_PATH to point to the location of "db2dsdriver.cfg"

 export DB2DSDRIVER_CFG_PATH=<PATH to db2dsdriver.cfg>

   b) test connection with DSN with IPv6 address
 python3 db2_conn_ssl_with_dsn.py 

-- RESULT:
Traceback (most recent call last):
  File "/tmp/aca_certs/aria-dev/db2_conn_ssl_with_dsn.py", line 35, in <module>
    main()
  File "/tmp/aca_certs/aria-dev/db2_conn_ssl_with_dsn.py", line 25, in main
    ibm_db_conn = ibm_db.connect(conn_str,'','')
Exception: [IBM][CLI Driver] SQL1531N  The connection failed because the name specified with the DSN connection string keyword could not be found in either the db2dsdriver.cfg configuration file or the db2cli.ini configuration file.  Data source name specified in the connection string: "ADPBASE". SQLCODE=-1531

3) Notes:
- if we map the IPv6 address to a fake hostname (in "/etc/hosts" file), and modify the "db2dsdriver.cfg" to replace 
the IPv6 address with hostname (see "test-hostname-db2dsdriver.cfg"), we can successfully connect using the "db2dsdriver.cfg".  

- similarly, if we use a DB2 server with IPv4 IP address in the "db2dsdriver.cfg", then test connection works.

Conclusion: This indicates the ibm_db driver doesn't seem to be able to read IPv6 addresses from the "db2dsdriver.cfg" file

**Comment by bimalkjha** [comment]
@sudhakar8488 I know about this issue with `IBM ODBC/CLI driver` which is used by `ibm_db` internally. Even the db2dsdriver.cfg file is read by clidriver and not ibm_db.
You can use db2cli.ini file instead of db2dsdriver.cfg file if it serves your purpose. IPV6 address is supported in ini file but not in cfg file.
You can add a db2cli.ini file with below contents:
```
$ cat db2cli.ini
[mydsn]
database=dbname;
hostname=IPV6_address
port=50000
uid=dbuserid
pwd=dbpasswd
```
You can add any other db2cli.ini keywords from this list too: https://www.ibm.com/docs/en/db2/11.5?topic=odbc-cliodbc-configuration-keywords if you have any requirement.
Once you configure db2cli.ini file, you can use `dsn=mydsn;` as connection string. Thanks.

**Comment by sudhakar8488** [comment]
Thank You. I am closing the issue.
